### ISSUE TITLE
[Feature Request] Highlight specific words sent from specific users

### ISSUE THREAD

**Issue by eps0003** [FrankerFaceZ/FrankerFaceZ#199] opened 2017-07-15 11:20 UTC
##**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: The FFZ Addon Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: The ability to only highlight keywords if they're sent from a specific user. I specifically want to highlight specific types of messages sent by the Mikuia bot, for example.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by Lordmau5** [comment] 2017-07-27 10:48
That feature is already implemented. Check "Chat Filtering" -> "Highlight Users" or alternative search for "highlight"
![image](https://user-images.githubusercontent.com/1345036/28666997-e9e3b0de-72c9-11e7-8c83-cb3409e36b96.png)

**Comment by SirStendec** [comment] 2017-09-22 03:42
This will be addressed in the v4 rewrite's advanced chat features. Dupe of #82

**Closed by SirStendec** 2017-09-22 03:42 UTC
