### ISSUE TITLE
[Feature Request] Multiple Mod Cards

### ISSUE THREAD

**Issue by Jahdoh** [FrankerFaceZ/FrankerFaceZ#226] opened 2017-09-12 17:23 UTC
**Web Browser**: Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Do you use BetterTTV or other Twitch extensions**: FFZ, and the FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: NA

**Bug / Idea**: Was curious if adding the ability to view multiple mod cards per channel would be possible; And the ability to resize them.

**Steps to Reproduce (if Applicable)**: Not a bug, but a UI issue on my end for resizing. Using a 4K monitor, I have to use page zoom in chrome (and windows) to read some text. If a twitch account has a long name, I can't access Controls, Chat History, Stats, or Name Changes portion of the card. Not sure if card resizing would help that. Having Multiple cards is just a quality of life feature for me. I use cards as flags when monitoring viewers in chat. (IE: Highlight when card open). There's always multiple viewers that I'd love to have cards up at the same time. _Addendum ^J_

**Comment by SirStendec** [comment] 2017-09-22 03:22
This is going to be addressed with the FFZv4 rewrite for the Twitch Beta website. Right now, Twitch owns the mod cards and it's hard-coded that there can only be one. For FFZv4, I'll be doing a full chat implementation (which is unfortunately necessary due to their boneheaded framework decision) and I'll be able to fix issues like only having one mod card when multiple would be super useful.

Closing this cause it's kind of a duplicate of a general "redo chat to be better in v4" thing.

**Closed by SirStendec** 2017-09-22 03:22 UTC
