### ISSUE TITLE
backbutton/mouse5 bug?

### ISSUE THREAD

**Issue by curryyy** [FrankerFaceZ/FrankerFaceZ#1016] opened 2021-03-24 02:41 UTC
hi since like 4 weeks the backbutton doesnt work anymore on "https://clips.twitch.tv/" 
i have to spam the button to get back to the previous website. 
when i disable the extension or revoke access to "https://clips.twitch.tv/" it works normally.
so far i tried: disabling all addons, deleting cookies and re-installing the extension with default settings.

i hope you can help !!

**Comment by SirStendec** [comment] 2021-03-24 16:56
I cannot reproduce this issue at all across two browsers and four settings profiles, including the extension's defaults.

This also isn't a valid issue report, so I'm just going to close this. If you're still having this issue, please open a proper issue.

**Closed by SirStendec** 2021-03-24 16:56 UTC
