### ISSUE TITLE
FFZ Interferes with Video Speed Changers such as Video Speed Controller

### ISSUE THREAD

**Issue by BobDaBilda** [FrankerFaceZ/FrankerFaceZ#829] opened 2020-06-29 05:40 UTC
**Describe the bug**
I watch VODs occasionally. When I do, I often speed them up (watching at 1.8x, etc.). When FFZ is enabled, I am unable to speed up VODs. I believe this may be because of your setting "Allow the player to speed up to reduce delay" under General under Player, as when this feature is enabled and my stream is "behind", my video speed controller will show the video playing at 1.04x speed, etc.. But disabling / enabling this setting does not allow me to speed up the video. I have to fully disable FFZ to allow the player to be sped up. 

**To Reproduce**
1. Open any VOD with FFZ installed and enabled, and Video Speed Controller by codebicycle installed and enabled.
2. Attempt to speed up the VOD with VSC
3. Your speed change will be ignored.

**Expected behavior**
I expect to be able to either enable or disable the "Allow the player to speed up to reduce delay" setting, and then be able to speed up VODs while it is en/disabled.

**Environment (please complete the following information):**
 I use "Video Speed Controller by codebicycle" to speed up VODs, I use it on Firefox (currently version 77.0.1), on Windows 10 Pro - Version 2004 - OS build 19041.329 with Windows Feature Experience Pack 120.2202.130.0 . If there is any other information that I could provide that would be helpful, let me know

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
I don't believe logs will help, but I can send them if necessary, I will be following this post, and be alerted to its update.

**Additional context**
I understand that this isn't really "your problem", and I do have a workaround, so this can be thought of as low-priority if it is not trivial to fix.

**Comment by SirStendec** [comment] 2020-07-05 17:49
Duplicate of #763 

In summary: This is a browser bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1517199) and not something within the scope of the extension to fix. You'll need to disable the audio compressor and reset player to recreate the HTML5 video element before adjusting playbackRate will have an effect.

**Closed by SirStendec** 2020-07-05 17:49 UTC
Labels: bug
