### ISSUE TITLE
Compressor causing volume to be incorrectly on 100 % when switching streams

### ISSUE THREAD

**Issue by Sachikoda** [FrankerFaceZ/FrankerFaceZ#820] opened 2020-06-13 10:56 UTC
**Describe the bug**
I have the volume of the twitch player set on 25 %. When I switch the streamer, the volume I hear is at 100 %, while the volume control still shows it being set on 25 %. I need to click on the control once to update the volume to 25 %. The problem didn't occure when I had the compressor deactivated, nor when I had FFZ deactivated as a whole.

**To Reproduce**
1. Open a stream and set the volume to something audibly quieter. 
2. Make sure the compressor is activated.
3. Switch the active stream via sidebar.
4. Click on the previously turned quieter volume control.
5. Notice the difference in the volume.

**Expected behavior**
The preset volume should be applied immediately when switching the stream. 

**Environment:**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.97
 - Other Extensions: uBlock Origin, Tab Muter

**FFZ Logs:**
[FFZ_Log.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/4774441/FFZ_Log.txt)

(had to upload it like this, since the Upload option doesn't seem to work for me)

**Additional context**
I couldn't quite reproduce this error when switching streams other than via the sidebar. Sometimes the volume was set correctly, sometimes the volume control was pushed to 100 % (aka it wasn't just as described above, but the control showed the volume to be wrong).

I hope I didn't mess up the report anywhere, I am completely new to GitHub :D

**Comment by Gamertech** [comment] 2020-06-20 05:50
Can confirm this. Happens every time after the watched channel hosts/raids another.

The volume bar stays where it was set, but the volume is actually set to 100%.

**Comment by SirStendec** [comment] 2020-06-23 18:15
I've done some testing, and this isn't entirely a FrankerFaceZ bug. Twitch's player resets its internal volume to 1. The problem is just that FFZ actually asks the player for its volume sometimes and expects it to answer correctly. Clearly this was a mistake on my part. I'm changing my code to pull the volume from the video element instead. Should be fixed in the next release.

**Closed** 2020-06-23 21:17 UTC
Labels: bug
