### ISSUE TITLE
Minimalistic Chat - No Heading bug

### ISSUE THREAD

**Issue by Sleekness** [FrankerFaceZ/FrankerFaceZ#178] opened 2017-06-19 21:24 UTC
**Web Browser**: Chrome 59

**Do you use BetterTTV or other Twitch extensions**: FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: Minimalistic Chat - No Heading is bugged. (http://i.imgur.com/0tuv5Vw.png). I used this option, but recently twitch changed something so it looks like this.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment] 2017-06-21 18:10
Duplicate of #175

**Closed by SirStendec** 2017-06-21 18:10 UTC
