### ISSUE TITLE
Emotes stack doesn't work with FFZ:AP

### ISSUE THREAD

**Issue by TheRealAldaris** [FrankerFaceZ/FrankerFaceZ#776] opened 2020-03-27 10:12 UTC
BTTV just released some new emotes that you stack with other emotes, but when FFZ:AP is enabled, it doesn't work.

Here's an example with FFZ:AP : 
![2020-03-27_111023](https://user-images.githubusercontent.com/28606292/77745590-d6e54900-701b-11ea-800e-11fbb5f30f98.png)

And without : 
![2020-03-27_111033](https://user-images.githubusercontent.com/28606292/77745608-df3d8400-701b-11ea-9f54-b35867ef863e.png)

**Comment by szernex** [comment] 2020-03-27 16:25
Having the same issue except even when I disable FFZ:AP and restart the browser it won't work still.

**Comment by SirStendec** [comment] 2020-03-27 18:48
BetterTTV's API does not expose information on which emotes are intended to act as overlays for other emotes. The maintainer of the BetterTTV Emotes add-on has to update the extension with hard-coded data for such emotes.

As far as I'm aware, he personally objects to the two emotes and refuses to support them. He has requested that BTTV add overlay information to their API so that there are not future situations similar to this and, as of 2pm EST, we've been told that it might be added.

As for szernex's response: When the BetterTTV Emotes add-on is disabled and BetterTTV's own extension is installed, the emote appears as intended by BTTV's developers so there is nothing to fix for core FrankerFaceZ.

You're specifically mentioning `FFZ:AP`, which leads me to believe you're using the old `FFZ:AP` browser extension. That is no longer used. To enable or disable add-ons that were formerly part of the add-on pack, you instead open the FFZ Control Center and navigate to Add-Ons. Just removing the old extension from your browser will not disable add-ons.


Closing this issue as it does not related to FrankerFaceZ itself but to an add-on. Unless Lordmau5 changes his decision, this likely won't be fixed unless and until such a time as BetterTTV adds the requested information to their API.

**Closed by SirStendec** 2020-03-27 18:48 UTC
Labels: invalid
