### ISSUE TITLE
New layout, some playback statistics no longer showing

### ISSUE THREAD

**Issue by BitGrub** [FrankerFaceZ/FrankerFaceZ#818] opened 2020-06-11 01:02 UTC
Specifically, stream delay monkaSad
![Screenshot_2020-06-11 Twitch](https://user-images.githubusercontent.com/20694416/84333365-3ae9c900-ab98-11ea-89fc-638a99fa2c95.png)

**Comment by drxt** [comment] 2020-06-11 02:45
PanicBasket

**Comment by toofar** [comment] 2020-06-11 05:00
In the meantime it looks like you can turn the new layout off for now: https://old.reddit.com/r/Twitch/comments/ghwf13/can_i_change_back_to_the_old_twitch_layout/fqdgc9k/

**Comment by pointydev** [comment] 2020-06-13 14:35
Duplicate of #794.

**Closed** 2020-07-01 00:07 UTC
