### ISSUE TITLE
Video player width does not adjust when chat width changes in theater mode.

### ISSUE THREAD

**Issue by Grendallmayo** [FrankerFaceZ/FrankerFaceZ#306] opened 2017-11-16 22:43 UTC
**Web Browser**: Google Chrome.

**Do you use BetterTTV or other Twitch extensions**: FFZ Add-On Pack (Doesn't matter, but felt like noting it.)

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When changing the chat width, the player does not adjust to fill the space, like it did in the original version of the extension.

**Steps to Reproduce (if Applicable)**:

**Comment by Doorstop2** [comment] 2017-11-16 23:00
Yeah its a Twitch thing idk if FFZ could fix it would be nice since its been like this for months 

its cause of there stupid whisper button which they could move in the bottom chat box and solve this problem

Source: https://twitter.com/twitchartiiz/status/878300523182538752 

"Temp Fix" LUL

**Comment by sisa1917** [comment] 2017-11-16 23:07
@Doorstop2 That is not the issue @Grendallmayo meant. He is talking about player WIDTH not the height, that is caused by changing the chat WIDTH.

**Comment by Doorstop2** [comment] 2017-11-16 23:22
Oh yeah your right i tested it not logged in the player wont scale changing chat width but if the player can fully fill the screen no matter what that would be great

**Comment by SirStendec** [comment] 2017-11-16 23:23
I cannot reproduce the issue on the current build. This was an issue when Chat Width was first implemented into v4 but it has since been addressed. Working:
![image](https://user-images.githubusercontent.com/14036657/32921302-1b250010-cafb-11e7-8914-2bc4fe51d910.png)
![image](https://user-images.githubusercontent.com/14036657/32921308-24ffa248-cafb-11e7-9fc4-cb15982940ab.png)

**Comment by sisa1917** [comment] 2017-11-16 23:27
I still experience the issue on Version 4.0.0-beta1.3 c89ba74a13dda449dfec (unless theres a new one available?)
![lg1k](https://user-images.githubusercontent.com/5894481/32921444-e6a374ce-cb2d-11e7-87ec-852915f365a5.png)

**Comment by SirStendec** [comment] 2017-11-16 23:33
Interesting. Can you right click the player, Inspect it, then find `<div class=".channel-page__video-player...">` in the list, select it, and take a screenshot including the Styles column?

Here's what it looks like for me, for reference:
![image](https://user-images.githubusercontent.com/14036657/32921710-7f049018-cafc-11e7-9bc6-3a6c5c7a7d52.png)

What I'm looking for is specifically something like 
![image](https://user-images.githubusercontent.com/14036657/32921723-8c90deda-cafc-11e7-9af7-fc79f0ebe048.png)

**Comment by Doorstop2** [comment] 2017-11-16 23:33
maybe this depends on monitor size also? mines 1920x1080 

![2017-11-16_18-30-38](https://user-images.githubusercontent.com/26550104/32921721-8b95619a-cafc-11e7-97ed-8ccdb9146669.png)

**Comment by SirStendec** [comment] 2017-11-16 23:34
Your screenshot isn't demonstrating the issue, Doorstop2. The player *is* filling all the available space, you can tell from the black background. It just doesn't stretch the video to fill it cause that'd be ugly and wrong and bad in every way.

**Comment by sisa1917** [comment] 2017-11-16 23:40
The div you asked for is full width 
![](https://files.gamegym.cz/u/N30p.jpg)

however I found class `persistent-player persistent-player--theatre` is not
![](https://files.gamegym.cz/u/kNpj.jpg)

**Comment by SirStendec** [comment] 2017-11-16 23:56
Interesting. It looks like Twitch is doing weird things for the Mini Player. Strange, I have the Mini Player enabled but it doesn't function. Still, this gives me enough to go on to write a fix. Should be live now, so let me know what you think.

The width might end up being wrong in theatre mode with chat collapsed. I have no way of testing that yet.

**Comment by sisa1917** [comment] 2017-11-16 23:59
Theater mode width is now correct and yes the width is wrong with collapsed chat. Thank you for the fast fix!

**Comment by SirStendec** [comment] 2017-11-17 00:04
Good enough for me. I'll worry about the width with collapsed chat when Twitch wants to actually give me the persistent player. I feel like most people would just use fullscreen at that point anyways, so it's not a big issue. Closing for now.

**Closed by SirStendec** 2017-11-17 00:04 UTC
