### ISSUE TITLE
Order of reason

### ISSUE THREAD

**Issue by Clementsly** [FrankerFaceZ/FrankerFaceZ#1405] opened 2023-09-08 21:04 UTC
Hello !! Can you made a fonction where I can move the order of the reason. In order to put higher the most usefull for me. Thx in advance 😉
Screen on discord : 
https://discord.com/channels/538253705661775872/538255779279536128/1149804890110042122

**Comment by SirStendec** [comment] 2023-09-08 22:48
Duplicate of #1404

**Closed by SirStendec** 2023-09-08 22:48 UTC
Labels: enhancement
