### ISSUE TITLE
Emotes not completing on typing after text.

### ISSUE THREAD

**Issue by Maverynthia** [FrankerFaceZ/FrankerFaceZ#1179] opened 2022-02-25 01:43 UTC
It used to be you could type
"Hello :smi" and then the list of emotes that started with or included 'smi' would show up. That no longer happens after text there is text in the box.

If it's the beginning of the text, then it works as intended. ":smi" will pull up the menu.

**Comment by Light-Passion** [comment] 2022-02-25 03:31
Can confirm, using Chrome.
Both @ and :  tab complete only function at start of text field, any text before fails with 'no matches.'

**Comment by NeonSilver** [comment] 2022-02-25 03:34
Can confirm as well.
Both @ and : tab complete only function at start of text field, any text before fails with 'no matches.'

Tested on Opera GX and Chrome

**Comment by palapula** [comment] 2022-02-25 04:58
Can confirm, on Edge. 
Same issues with @ and : complete at the beginning of a text box. Also noticed after completing an @ command, if I then use an emote with : the @ username window will open and close sporadically.

**Comment by Fittiboy** [comment] 2022-02-25 06:47
Same here, plus more! By using the Inline Tab Add-On, I used to be able to autocomplete emotes without : _and_ autocomplete usernames without @. Now I can no longer autocomplete emotes without :, even at the start of the text box!

**Comment by mushweed** [comment] 2022-02-25 09:19
![grafik](https://user-images.githubusercontent.com/24358061/155689060-88c250f3-1fef-4936-917e-aa408a49c98c.png)

Can confirm on Firefox aswell

**Comment by auloen** [comment] 2022-02-25 10:40
i ruined my ffz setting thought is was just some setting problem. please fix

**Comment by Lordmau5** [comment] 2022-02-25 14:09
As it was mentioned on the FFZ Discord already, this is an issue on Twitch's end that we can't fix.

They are currently experimenting with a WYSIWYG ("What You See Is What You Get") editor that (from what I've heard) should put the actual emotes into the text box, so I'd assume that's part of the reason why it broke.

**Comment by DorCoMaNdO** [comment] 2022-02-25 21:27
> As it was mentioned on the FFZ Discord already, this is an issue on Twitch's end that we can't fix.
> 
> They are currently experimenting with a WYSIWYG ("What You See Is What You Get") editor that (from what I've heard) should put the actual emotes into the text box, so I'd assume that's part of the reason why it broke.

Yep, confirmed fixed with WYSIWYG experiment enabled.

**Comment by Lordmau5** [comment] 2022-02-26 09:15
A couple more users mentioned in the Discord that it's fixed for them, both Stendec and I could also confirm it was fixed on our end.

I'm gonna close this issue for now - if it comes up again we'll either reopen it or someone can just do a new one :)

**Closed by Lordmau5** 2022-02-26 09:15 UTC
Labels: bug, twitch-bug
