### ISSUE TITLE
[Bug] Error loading data

### ISSUE THREAD

**Issue by Bobrozzoid** [FrankerFaceZ/FrankerFaceZ#414] opened 2018-04-10 20:10 UTC
**Web Browser**: Chrome 64.0.3282.119

**Do you use BetterTTV or other Twitch extensions**: No

**Bug**:
Getting error loading data when browsing directories, same in firefox
![ss 2018-04-10 at 11 08 53](https://user-images.githubusercontent.com/38256624/38581077-660dafba-3d14-11e8-9fdb-a0845476b237.png)

**Comment by SirStendec** [comment] 2018-04-10 20:12
Please open your browser's developer console (Ctrl-Shift-J if you're a windows users) and take screenshots of any red error messages.

**Comment by Bobrozzoid** [comment] 2018-04-10 20:17
![ss 2018-04-10 at 11 15 56](https://user-images.githubusercontent.com/38256624/38581367-58644dbe-3d15-11e8-92a4-d077a9f32c3d.png)
![ss 2018-04-10 at 11 16 30](https://user-images.githubusercontent.com/38256624/38581368-587e3ff8-3d15-11e8-86ba-7e3c537e13df.png)
![ss 2018-04-10 at 11 17 01](https://user-images.githubusercontent.com/38256624/38581371-5897806c-3d15-11e8-8aa4-8b30550c7268.png)

**Comment by jaaneh** [comment] 2018-04-10 22:35
Adding my screenshot here too, as I'm faced with the same issue.

![wws2h](https://user-images.githubusercontent.com/27323317/38586912-f0d639ae-3d1f-11e8-9776-68067831b0f2.png)

**Comment by pahakalle** [comment] 2018-04-10 22:37
Are you running any adblock or that kind of extension, if yes try turning them off and try again. 
Hard refresh might also help

**Comment by jaaneh** [comment] 2018-04-10 22:44
@pahakalle tried with/without adblock, with/without other addons. Only thing that fixes is to disable FFZ

**Comment by SirStendec** [comment] 2018-04-11 01:14
I just pushed out build 4.0.0-beta2.4@b3fb24504616675ad2b9 that might fix this issue. Let me know if you're still seeing it. I haven't been able to reproduce it myself.

**Comment by Bobrozzoid** [comment] 2018-04-11 02:31
Well, for me it definitely solved the problem, and now its working :)

**Comment by jaaneh** [comment] 2018-04-11 07:08
Seems like it works on my end as well!

**Comment by SirStendec** [comment] 2018-04-11 16:06
I'm not satisfied with how it was fixed, but a rewrite of how I'm modifying queries will have to wait for a later time when there's not so much to do. Closing this for now as it seems to be resolved.

**Closed by SirStendec** 2018-04-11 16:06 UTC
