### ISSUE TITLE
Stream Latency display disappeared

### ISSUE THREAD

**Issue by GeekBoyMN** [FrankerFaceZ/FrankerFaceZ#790] opened 2020-04-24 06:58 UTC
The stream latency display suddenly stopped showing up in Chrome. I checked in the Control Center and the option is still enabled. I've restarted Chrome several times but the latency counter doesn't come back. On another PC with the same build of Windows 10, same version of Chrome and all settings matched the latency display works properly. My main machine with the issue was built with a fresh Windows 10 installation 6 days ago, and the 2nd machine was just loaded with fresh Windows 10 today. Both are Pro build 1909 and fully updated. The latency display was working fine until today. 

**To Reproduce**
Open Chrome and navigate to any Twitch stream.

**Expected behavior**
The latency display provided by FFZ was working fine since installing Windows on this newly built PC until today when it stopped for no apparent reason. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro version 1909 build 18363.778
 - Browser Chrome Version 81.0.4044.122 (Official Build) (64-bit)
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
[1:33:19] info | core: FrankerFaceZ v4.19.10 (build 1c82256e5ea6000f03ae - commit 13af2f304697b9e71d5abfcd79561815059e6994)
[1:33:19] info | settings: Using Provider: LocalStorageProvider
[1:33:19] info | site: Using: Twilight
[1:33:19] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[1:33:19] info | core: Loaded descriptions of 6 modules.
[1:33:19] info | site.fine: Installing MutationObserver.
[1:33:19] info | site: Loaded descriptions of 18 modules.
[1:33:19] info | settings: Initialization complete after 39.22000ms -- Values: 6 -- Profiles: 2
[1:33:19] info | socket: Using Server: wss://tuturu.frankerfacez.com/
[1:33:19] info | raven: Installed error tracking.
[1:33:19] info | site.switchboard: Found Route and Switch with 13 routes.
[1:33:19] info | site.switchboard: Found Non-Matching Route /event/:teamName
[1:33:19] warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: Cannot read property 'match' of undefined
[1:33:19] info | site.switchboard: Found Non-Matching Route /partner/signup
[1:33:19] info | site.web_munch: require() grabbed from invocation of module pnJH
[1:33:19] info | site.web_munch: require() grabbed in 57.56000ms.
[1:33:19] info | site.web_munch: Loaded names for 441 chunks from require().
[1:33:19] info | main_menu: Built Tree in 15.79000ms with 126 structure nodes and 196 settings nodes.
[1:33:19] info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[1:33:19] info | experiments: Loaded information on 1 experiments.
[1:33:19] info | core: Initialization complete in 490.36500ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.side-nav.hide-offline: false
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
channel.metadata.force-above: false
layout.portrait-invert: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 5
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
directory.show-channel-avatars: true
directory.hide-live: false
chat.width: 340
chat.use-width: false
player.theatre.auto-enter: false
player.no-autoplay: false
player.home.autoplay: false
player.button.pip: false
player.button.reset: true
player.allow-catchup: true
player.hide-squad-banner: false
metadata.host-button: true
metadata.featured-follow: true
channel.hosting.enable: true
chat.bits.show: true
layout.display-bits-button: true
metadata.uptime: 1
metadata.player-stats: true
ffz.show-new-settings: true
layout.is-minimal: false
channel.raids.no-autojoin: false
metadata.stream-delay-warning: 0
sub-button.prime-notice: false

raven
-------------------------------------------------------------------------------
[3:01:50] HTTP | fetch: GET //api.frankerfacez.com/v1/room/id/35049291 -> 404
[3:01:50] LOG:info | socket: Connected.
[3:01:50] HTTP | fetch: GET https://cdn.frankerfacez.com/script/emoji/v2-.json?_1587709980 -> 200
[3:01:50] LOG:info | chat.badges: Added "developer" to 2 users.
[3:01:50] LOG:info | chat.badges: Added "bot" to 138 users.
[3:01:50] LOG:info | chat.badges: Added "supporter" to 21066 users.
[3:01:50] LOG:info | chat.badges: Loaded 3 badges and assigned them to 21206 users.
[3:01:50] LOG:info | chat.emotes: Loaded emote set #3: Global Emotes (11 emotes)
[3:01:50] LOG:info | chat.emotes: Loaded emote set #4330: : Sten's Cheaty Emotes (3 emotes)
[3:01:50] LOG:info | chat.emotes: Added ": Sten's Cheaty Emotes" emote set to 1 users.
[3:01:50] LOG:info | chat.emoji: Loaded data about 1568 emoji.
[3:01:50] LOG:info | gql: VerifyEmail_CurrentUser [25ms]
    {}
[3:01:50] LOG:info | gql: ProvideEmail_CurrentUser [25ms]
    {}
[3:01:50] LOG:info | gql: CollaborationBanner [23ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] LOG:info | gql: ChannelPanels [42ms]
    {"variables":{"id":"35049291"}}
[3:01:50] LOG:info | gql: Whispers_Whispers_UserWhisperThreads [82ms]
    {"variables":{}}
[3:01:50] LOG:info | gql: RealtimeStreamTagList [76ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] LOG:info | gql: ChannelPage_SubscribeButton_User [159ms]
    {"variables":{"withOffers":false,"login":"talon"}}
[3:01:50] LOG:info | gql: Chat_OrbisPresetText [39ms]
    {"variables":{"login":"talon"}}
[3:01:50] LOG:info | gql: NewChatterRitual_Channel [39ms]
    {"variables":{"id":"35049291"}}
[3:01:50] LOG:info | gql: EmotePicker_EmotePicker_UserSubscriptionProducts [69ms]
    {"variables":{"channelOwnerID":"35049291"}}
[3:01:50] LOG:info | gql: BitsCard_Bits [69ms]
    {}
[3:01:50] LOG:info | gql: CommunityPointsAvailableClaim [56ms]
    {"variables":{"channelID":"35049291"}}
[3:01:50] LOG:info | gql: ChannelLeaderboards [53ms]
    {"variables":{"channelID":"35049291"}}
[3:01:50] LOG:info | gql: GetHypeTrainExecution [65ms]
    {"variables":{"userLogin":"talon"}}
[3:01:50] LOG:info | gql: UseLive [40ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] LOG:info | gql: DropsHighlightService_AvailableDrops [35ms]
    {"variables":{"channelID":"35049291"}}
[3:01:50] LOG:info | gql: Chat_ShareBitsBadgeTier_ChannelData [22ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] LOG:info | gql: Chat_ShareResub_ChannelData [47ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] LOG:info | socket: Server Time: 2020-04-24T06:33:20.165Z
[3:01:50] LOG:info | socket:  Local Time: 2020-04-24T06:33:20.631Z
[3:01:50] LOG:info | socket:   Est. Ping: 262.57250ms
[3:01:50] LOG:info | socket: Time Offset: 0.20296142578125
[3:01:50] HTTP | fetch: GET https://api.twitch.tv/v5/bits/extensions/twitch.ext.bttsqjy6dnv05acplp5vy0mflgrh3z/products -> 200
[3:01:50] LOG:info | gql: Core_Services_Spade_CurrentUser [25ms]
    {}
[3:01:50] LOG:info | gql: FFZ_StreamFetch [38ms]
    {"variables":{"ids":["35049291"],"logins":null}}
[3:01:50] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:01:50] LOG:info | gql: SubModal [166ms]
    {"variables":{"withOffers":false,"includeEmoteModifiers":false,"login":"talon"}}
[3:01:50] LOG:info | gql: ChannelLeaderboards_LeaderboardEntry [22ms]
    {"variables":{"userID":"35843978"}}
[3:01:50] LOG:info | gql: ChannelLeaderboards_LeaderboardEntry [22ms]
    {"variables":{"userID":"57238976"}}
[3:01:50] LOG:info | gql: ChannelLeaderboards_LeaderboardEntry [22ms]
    {"variables":{"userID":"45253414"}}
[3:01:50] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:01:50] LOG:info | settings: Successfully refreshed 0 of 0 profiles from remote URLs.
[3:01:50] UI | ui.click: span.ffz-stat-text
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] LOG:info | site.compat_emote_menu: Emote Menu for Twitch was not found after 60 seconds.
[3:01:50] LOG:info | gql: updateUserViewedVideo [57ms]
    {"variables":{"input":{"userID":"59576387","position":12354,"videoID":"37705701584","videoType":"LIVE"}}}
[3:01:50] LOG:info | gql: GetBitsButton_Bits [78ms]
    {"variables":{"login":null,"withChannel":false,"isLoggedIn":true}}
[3:01:50] LOG:info | gql: BitsConfigContext_Global [7ms]
    {}
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:01:50] UI | ui.click: div.tw-align-items-center.tw-flex.tw-pd-05.tw-relative > div.tw-flex-grow-1
[3:01:50] LOG:info | main_menu: Built Tree in 9.00500ms with 126 structure nodes and 196 settings nodes.
[3:01:50] UI | ui.click: span.tw-flex-grow-1
[3:01:50] UI | ui.click: span.tw-flex-grow-1
[3:01:50] UI | ui.click: span.tw-flex-grow-1
[3:01:50] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[3:01:50] UI | ui.click: input#setting:metadata.player-stats.tw-checkbox__input[type="checkbox"]
[3:01:50] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[3:01:50] UI | ui.click: input#setting:metadata.player-stats.tw-checkbox__input[type="checkbox"]
[3:01:50] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[3:01:50] UI | ui.click: input#setting:sub-button.prime-notice.tw-checkbox__input[type="checkbox"]
[3:01:50] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[3:01:50] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[3:01:50] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:01:50] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=779416161943853431&instrumentation=%7B%22init-began-at%22%3A%221082%22%2C%22%2Fv1%2Fpageview-brtt%22%3A%22278%22%2C%22%2F_r-brtt%22%3A%221100%22%2C%22%2Fv1%2Fopen-brtt%22%3A%22189%22%2C%22%2Fv2%2Fevent%2Fcustom-brtt%22%3A%22370%22%7D -> 200
[3:01:50] LOG:info | gql: FollowedChannels [101ms]
    {"variables":{"limit":100,"cursor":""}}
[3:01:50] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.click: div.simplebar-scroll-content > div.simplebar-content
[3:01:50] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:01:50] UI | ui.click: button.tw-align-items-center.tw-align-middle.tw-border-bottom-left-radius-medium.tw-border-bottom-right-radius-medium.tw-border-top-left-radius-medium.tw-border-top-right-radius-medium.tw-button-icon.tw-button-icon--secondary.tw-core-button.tw-inline-flex.tw-interactive.tw-justify-content-center.tw-overflow-hidden.tw-relative
[3:01:50] LOG:info | gql: FFZ_EmoteMenu_SubStatus [123ms]
    {"variables":{"first":75,"after":null,"criteria":{"filter":"ALL"}}}
[3:01:50] UI | ui.click: button.ffz-tooltip.emote-picker__emote-link
[3:01:50] UI | ui.click: div.tw-flex-grow-0
[3:01:50] UI | ui.click: span.tw-mg-r-05 > figure.ffz-i-clock
[3:01:50] LOG:info | gql: FFZ_BroadcastID [62ms]
    {"variables":{"id":"35049291"}}
[3:01:50] UI | ui.click: h2.tw-font-size-4.tw-line-height-body[title="DayZ Running "]
[3:01:50] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:01:50] LOG:info | main_menu: Built Tree in 7.51000ms with 126 structure nodes and 196 settings nodes.
[3:01:50] UI | ui.click: input#player-volume-slider-293ec0c0-a6e3-424b-b2a4-03b136e3103b.tw-range.tw-range--overlay[type="range"]
[3:01:50] LOG:info | gql: FollowedChannels [116ms]
    {"variables":{"limit":100,"cursor":""}}
[3:01:50] UI | ui.click: span.tw-flex-grow-1
[3:01:50] UI | ui.click: span.tw-flex-grow-1
[3:01:50] HTTP | fetch: GET https://api.github.com/repos/frankerfacez/frankerfacez/commits -> 200
[3:01:50] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:01:50] LOG:info | gql: RealtimeStreamTagList [76ms]
    {"variables":{"channelLogin":"talon"}}
[3:01:50] UI | ui.click: span.tw-flex-grow-1

experiments
-------------------------------------------------------------------------------
Unique ID: d422727a97842413

FFZ | New API Stress Testing: true
TWITCH | vx_aa_logged_out: control_a
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: control
TWITCH | paypal_first_v2: control
TWITCH | ABRNetworkLinkFilter: control
TWITCH | twilight_settings_labelling: rest
TWITCH | player_core_ad_loudness: control
TWITCH | its_the_remix_to_position: variant7
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | missing_boxart: variant
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: control
TWITCH | take_the_leaderboard: TakeTop10Spot
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | vx_aa_logged_in: control_a
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: variant1
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: control
TWITCH | disco_directory_titles: variant1
TWITCH | prowse_li: variant1
TWITCH | disco_max_width: variant1
TWITCH | vxp_thunderdome: control
TWITCH | community-gifting-reduce-friction: control
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | vx_aa_all: control_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | sub_mgmt_modal: variant
TWITCH | TWILIGHT_AAX_DISPLAY: yes
TWITCH | watch_stunt_double: control
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: control
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-b
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | chat_input_revamp: variant1
TWITCH | Twilight Player Core NPM Distribution (Public): variant-b
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | ABRObserveredBitrates: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: one_line_no_avatar
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | fpso: variant_50
TWITCH | extension_overlay_improvement: control
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | ad_affiliate_rev_share: treatment
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: variant1
TWITCH | liverecs_holdout_device: control
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | vxp_mandatory_email_verification: control
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: control
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | watch_stunt_double_user: control
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: control
TWITCH | abr_fastslow_web: control
TWITCH | twilight_stream_summary_use_kite: no
TWITCH | Devsite_create_apps_form_recaptcha: variant1
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | placement_promotions_pos: control
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | subs_pif: gift_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | chat_rejoin_rewrite: variant
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | disabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.9

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.emote-menu.sort-emotes: 0
chat.emote-menu.sort-tiers-last: true
chat.fix-bad-emotes: true
chat.actions.room-above: false
chat.actions.room: []
chat.tab-complete.emotes-without-colon: false
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: true
chat.lines.alternate: false
chat.lines.padding: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.points.show-button: true
chat.points.show-rewards: true
chat.width: 340
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.bits.animated: true
theme.tooltips-dark: false
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.polls: true
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.points.auto-rewards: undefined
chat.mru.enabled: true
chat.filtering.process-own: false
chat.filtering.display-deleted: false
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.all-links: false
chat.timestamp-format: "h:mm"
chat.badges.hidden: {}
chat.badges.custom-mod: true
tooltip.images: true
tooltip.badge-images: true
chat.filtering.highlight-basic-users-blocked: []
chat.filtering.highlight-basic-users-blocked--regex: null
chat.filtering.highlight-basic-badges-blocked: []
chat.filtering.highlight-basic-badges-blocked--list: null
chat.filtering.highlight-basic-blocked: []
chat.filtering.highlight-basic-blocked--regex: null
chat.filtering.highlight-basic-users: []
chat.filtering.highlight-basic-users--color-regex: null
chat.filtering.highlight-basic-badges: []
chat.filtering.highlight-basic-badges--colors: null
chat.filtering.highlight-basic-terms: []
chat.filtering.highlight-basic-terms--color-regex: null
chat.emote-menu.reduced-padding: false
chat.emote-menu.combine-tabs: false
chat.emote-menu.default-tab: "channel"
chat.emote-menu.show-search: true
chat.emote-menu.show-heading: 1
tooltip.emote-images: true
chat.click-emotes: true
chat.sub-emotes: true
chat.emote-dialogs: true
**Additional context**

**Comment by SirStendec** [comment] 2020-04-24 15:23
I believe this should be fixed as of b3266a2ef37c376a78dd7662d7a35bf2d60f0093

This is caused by the same thing as #789. Let me know if it's not fixed for you on the new update and I'll reopen this.

**Closed by SirStendec** 2020-04-24 15:23 UTC
Labels: bug

**Comment by GeekBoyMN** [comment] 2020-04-24 18:34
It's working. Thanks!

**Comment by TeeJay69** [comment] 2025-05-21 15:39
Sorry, but how do i get the newest version? In chrome web store it says latest release is march 31, even for the nightly build.
