### ISSUE TITLE
Cheermotes are not showing up.

### ISSUE THREAD

**Issue by lluvdwayulie** [FrankerFaceZ/FrankerFaceZ#174] opened 2017-06-11 01:50 UTC
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ Add On Pack. I deactivated that and it still doesn't load.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NjEzNw.log

**Bug / Idea**: Any cheermotes other than the basic cheer GIF does not load in my chat. I just get a blank/transparent image followed by the number of bits cheered.

**Steps to Reproduce (if Applicable)**: Go to chat, cheer/see someone's cheer.

**Comment by SirStendec** [comment] 2017-06-11 17:32
This seems likely to be an issue with your connection. I can't reproduce this bug at all. Closing this unless and until you can provide a way to reproduce it.

**Closed by SirStendec** 2017-06-11 17:32 UTC
Labels: invalid

**Comment by lluvdwayulie** [comment] 2017-06-26 20:54
Just saw this. I deactivated FFZ and it loaded properly. I tried uninstalling and reinstalling FFZ but it still does not load, so I don't know what's the problem but I don't think it's on my end.

**Comment by Psychoboy** [comment] 2019-07-25 00:37
I know this is a long issue I am having same issue. I uninstall FFZ and the BTTV addon and it works. I install BTTV and it works just fine. but with FFZ they do now.
