### ISSUE TITLE
Added 7TV emotes are not being displayed in mod view

### ISSUE THREAD

**Issue by blitzluchsy** [FrankerFaceZ/FrankerFaceZ#1475] opened 2024-03-20 14:34 UTC
**Describe the bug**
Whenever I add a 7TV emoji it posts a message in the chat but the message is blank and I can't see the added emoji

**To Reproduce**
1. Go to your FFZ settings and add the 7tv extension
2. Add a new emoji in 7TV

**Expected behavior**
It should display the added emoji just like the 7TV extension does

![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/87650896/ef684ea4-3ed2-4e32-ae50-d0339c15d701)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 122.0.6261.129
 - Other Extensions: ublock origin (disabled for twitch though)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
[logs.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/14668023/logs.txt)

**Comment by SirStendec** [comment] 2024-03-20 16:14
Having trouble reproducing this. From your screenshot, it looks like there was some kind of error rendering the chat line so it fell back to Twitch rendering, which doesn't understand how to display that message type so it just looks blank.

Can you open your browser's console (F12) and check for red error messages that appear when one of these comes through? Thanks.

**Comment by blitzluchsy** [comment] 2024-03-20 20:19
Hey, so this is the error I am getting
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/87650896/8be19a09-6d2b-4b5c-88cd-685d79e76f4b)

**Comment by SirStendec** [comment] 2024-03-20 20:28
Ah, it looks like a compatibility issue with the Repetition Detector add-on. That'd explain why I can't reproduce the issue locally. I know what's happening, and it'll be fixed in the next FFZ update.

**Comment by blitzluchsy** [comment] 2024-03-20 20:53
Thank you very much. Have a great day <3

**Closed** 2024-03-21 19:44 UTC
Labels: bug
