### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Umgak** [FrankerFaceZ/FrankerFaceZ#493] opened 2018-07-23 20:53 UTC
An option to disable or change the appearance of the Get Bits button in the top navigation bar would be appreciated. In its current form, the Get Bits button clashes heavily with the icons in the area, and in my opinion it's quite unsightly.

**Comment by SirStendec** [comment] 2018-07-23 21:15
Not hiding the button is a regression caused by Twitch removing the element selectors used to target the button. This has been fixed in 30519a7377a98796bcbd4c12bf2db8b206210834

**Closed by SirStendec** 2018-07-23 21:15 UTC
Labels: bug
