### ISSUE TITLE
Layout changed, FFZ features missing

### ISSUE THREAD

**Issue by GeekBoyMN** [FrankerFaceZ/FrankerFaceZ#796] opened 2020-05-10 23:36 UTC
Since Thursday May 7 2020 the "host" button and the latency display that normally reside just below the stream window have vanished, and the uptime display no longer shows the stream start time on pointer hovering as it did before. Everything was fine early that morning, but when I went back on Twitch that afternoon, it was all different. Several Twitch features that used to be at the top of the screen are now at the bottom which I suspect is what changed the FFZ stuff. I've checked the FFZ control panel to confirm my settings and they are exactly as I expect, statistics (latency) is still checked as is "host" button. 
 This is happening in Chrome and FireFox on 4 different machines: Newly built Asus based Ryzen 5 system, Gigabyte based Phenom II, Dell i7 and Asus i5 laptops. The Asus laptop has a 4 month old Win 10 Pro 1909 install, the other 3 have had Win 10 Pro 1909 installed less than a month each. 

**To Reproduce**
1. Go to twitch.tv
2. Click on any live stream
3. Scroll down to just below the live stream window

**Expected behavior**
Expect to see FFZ features such as latency display, "host" button, but they are gone

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro build 1909
 - Browser Chrome and FireFox
 - Version newest versions of both as well as updated extensions
 - Other Extensions: [e.g. BetterTTV, Disable HTML5 Autoplay (disabled on Twitch), AdBlock, etc.]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
[18:15:48] info | core: FrankerFaceZ v4.19.11 (build 2e5a3b42617fb07be342 - commit b3266a2ef37c376a78dd7662d7a35bf2d60f0093)
[18:15:48] info | settings: Using Provider: LocalStorageProvider
[18:15:48] info | site: Using: Twilight
[18:15:48] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[18:15:48] info | core: Loaded descriptions of 6 modules.
[18:15:48] info | site.fine: Installing MutationObserver.
[18:15:48] info | site: Loaded descriptions of 18 modules.
[18:15:48] info | settings: Initialization complete after 60.30500ms -- Values: 12 -- Profiles: 2
[18:15:48] info | socket: Using Server: wss://yoohoo.frankerfacez.com/
[18:15:48] info | raven: Installed error tracking.
[18:15:48] info | site.switchboard: Found Route and Switch with 13 routes.
[18:15:48] info | site.switchboard: Found Non-Matching Route /event/:teamName
[18:15:48] warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: Cannot read property 'match' of undefined
[18:15:48] info | site.switchboard: Found Non-Matching Route /partner/signup
[18:15:48] info | site.web_munch: require() grabbed from invocation of module uHYy
[18:15:48] info | site.web_munch: require() grabbed in 168.62500ms.
[18:15:48] info | site.web_munch: Loaded names for 450 chunks from require().
[18:15:48] info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[18:15:49] info | main_menu: Built Tree in 15.24000ms with 126 structure nodes and 196 settings nodes.
[18:15:49] info | experiments: Loaded information on 1 experiments.
[18:15:49] info | site.player: Unable to immediately pause. Listening for playing event.
[18:15:49] info | core: Initialization complete in 556.15000ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.side-nav.hide-offline: false
layout.prime-offers: false
layout.discover: false
channel.round-avatars: true
channel.hide-not-live-bar: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
channel.metadata.force-above: true
layout.portrait-invert: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 5
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
player.no-autoplay: false
player.home.autoplay: false
player.button.pip: false
player.button.reset: true
player.compressor.enable: true
player.allow-catchup: true
player.compressor.default: false
directory.show-channel-avatars: true
directory.hide-live: false
chat.width: 340
chat.use-width: false
chat.bits.show: true
layout.display-bits-button: true
ffz.show-new-settings: true
player.theatre.auto-enter: false
metadata.host-button: true

raven
-------------------------------------------------------------------------------
[3:25:52] LOG:info | gql: CommunityPointsRewardRedemptionContext [28ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: PollsEnabled [40ms]
    {"variables":{"login":"timmy_t5"}}
[3:25:52] LOG:info | gql: ChatList_Badges [54ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: CurrentUserBannedStatus [25ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: ChatInput [74ms]
    {"variables":{"channelLogin":"timmy_t5","isEmbedded":false}}
[3:25:52] LOG:info | gql: ChatRestrictions [43ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: MessageBuffer_Channel [28ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: BlockedUsers [57ms]
    {}
[3:25:52] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:25:52] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:25:52] HTTP | fetch: GET //api-test.frankerfacez.com/v1/room/id/94739942 -> 404
[3:25:52] HTTP | fetch: GET //api.frankerfacez.com/v1/room/id/94739942 -> 404
[3:25:52] LOG:info | gql: ChannelPage_SubscribeButton_User [159ms]
    {"variables":{"withOffers":false,"login":"timmy_t5"}}
[3:25:52] LOG:info | gql: Chat_OrbisPresetText [38ms]
    {"variables":{"login":"timmy_t5"}}
[3:25:52] LOG:info | gql: VideoMarkersChatCommand [38ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: ExtensionsForChannelCurrentUser [27ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: StreamRefetchManager [38ms]
    {"variables":{"channel":"timmy_t5"}}
[3:25:52] HTTP | xhr: GET https://api.betterttv.net/3/cached/users/twitch/94739942 -> 200
[3:25:52] LOG:info | gql: Chat_ShareBitsBadgeTier_ChannelData [31ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: Chat_ShareResub_ChannelData [27ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: ActiveWatchParty [48ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: ChannelEditButton [41ms]
    {}
[3:25:52] HTTP | xhr: GET https://api.betterttv.net/3/cached/frankerfacez/users/twitch/94739942 -> 200
[3:25:52] HTTP | xhr: GET https://tmi.twitch.tv/hosts?host=59576387 -> 200
[3:25:52] LOG:info | gql: UserModStatus [27ms]
    {"variables":{"channelID":"94739942","userID":"59576387"}}
[3:25:52] LOG:info | gql: SelfModStatus [27ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: SubBenefitReminder_SubscriptionDetails [30ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: EmotePicker_EmotePicker_UserSubscriptionProducts [67ms]
    {"variables":{"channelOwnerID":"94739942"}}
[3:25:52] LOG:info | gql: ChatRoomBanStatus [20ms]
    {"variables":{"channelID":"94739942","targetUserID":"59576387"}}
[3:25:52] LOG:info | gql: CommunityPointsAvailableClaim [57ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: ChannelPollContext_GetViewablePoll [67ms]
    {"variables":{"login":"timmy_t5"}}
[3:25:52] LOG:info | gql: BitsCard_Bits [67ms]
    {}
[3:25:52] LOG:info | gql: ChannelRoot_SocialMediaSpace [78ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: NewChatterRitual_Channel [39ms]
    {"variables":{"id":"94739942"}}
[3:25:52] LOG:info | gql: ChannelLeaderboards [53ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: GetHypeTrainExecution [56ms]
    {"variables":{"userLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: UseLive [39ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:52] LOG:info | gql: DropsHighlightService_AvailableDrops [28ms]
    {"variables":{"channelID":"94739942"}}
[3:25:52] LOG:info | gql: SubModal [169ms]
    {"variables":{"withOffers":false,"includeEmoteModifiers":false,"login":"timmy_t5"}}
[3:25:52] LOG:info | gql: ChannelLeaderboards_LeaderboardEntry [19ms]
    {"variables":{"userID":"100527103"}}
[3:25:52] LOG:info | gql: ChannelLeaderboards_LeaderboardEntry [19ms]
    {"variables":{"userID":"64028389"}}
[3:25:52] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:25:52] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=779416161943853431&instrumentation=%7B%22init-began-at%22%3A%223774%22%2C%22%2Fv1%2Fpageview-brtt%22%3A%22419%22%2C%22%2F_r-brtt%22%3A%22414%22%2C%22%2Fv1%2Fopen-brtt%22%3A%22140%22%2C%22%2Fv2%2Fevent%2Fcustom-brtt%22%3A%22146%22%7D -> 200
[3:25:52] UI | ui.click: input#player-volume-slider-b461bc9c-2c1d-4864-b7d6-62c4790bcce7.tw-range.tw-range--overlay[type="range"]
[3:25:52] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:25:52] LOG:info | gql: FFZ_EmoteMenu_SubStatus [97ms]
    {"variables":{"first":75,"after":null,"criteria":{"filter":"ALL"}}}
[3:25:52] UI | ui.click: button.ffz-tooltip.emote-picker__emote-link
[3:25:52] UI | ui.click: button.ffz-tooltip.emote-picker__emote-link
[3:25:52] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:25:52] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.click: div.tw-flex-grow-0
[3:25:52] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] LOG:info | site.compat_emote_menu: Emote Menu for Twitch was not found after 60 seconds.
[3:25:52] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] LOG:info | gql: updateUserViewedVideo [43ms]
    {"variables":{"input":{"userID":"59576387","position":10236,"videoID":"37979119696","videoType":"LIVE"}}}
[3:25:52] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:25:52] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:25:52] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:25:52] LOG:info | gql: FollowedChannels [93ms]
    {"variables":{"limit":100,"cursor":""}}
[3:25:52] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:25:52] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:25:52] LOG:info | gql: TopNavUserMenuDropdownQuery [64ms]
    {"variables":{"login":"geekboymn"}}
[3:25:52] LOG:info | gql: GetBitsButton_Bits [117ms]
    {"variables":{"login":"","withChannel":false,"isLoggedIn":true}}
[3:25:52] LOG:info | gql: BitsConfigContext_Global [6ms]
    {}
[3:25:52] UI | ui.click: img.tw-block.tw-border-radius-rounded.tw-image.tw-image-avatar[alt="User Avatar"]
[3:25:52] UI | ui.click: div.tw-align-items-center.tw-flex > div.tw-toggle > label.tw-toggle__button
[3:25:52] UI | ui.click: input#c0e40d807ff0ec6ccba633b01bb54ec5.tw-toggle__input[type="checkbox"]
[3:25:52] LOG:info | gql: TopNav_User_UpdateVisibility [51ms]
    {"variables":{"input":{"visibility":"ONLINE"}}}
[3:25:52] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:25:52] LOG:info | main_menu: Built Tree in 6.93500ms with 126 structure nodes and 196 settings nodes.
[3:25:52] UI | ui.click: span.tw-flex-grow-1
[3:25:52] UI | ui.click: div.tw-c-background-alt-2.tw-font-size-5.tw-pd-y-05.tw-pd-x-1.tw-border-radius-large
[3:25:52] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[3:25:52] UI | ui.click: div.ffz--menu-page > div > div.ffz--menu-container.tw-border-t
[3:25:52] LOG:info | gql: IncomingRaidLine_Channel [21ms]
    {"variables":{"channelLogin":"thefinalboss_"}}
[3:25:52] UI | ui.click: div.simplebar-scroll-content > div.simplebar-content > div.ffz--menu-page
[3:25:52] UI | ui.click: div.simplebar-scroll-content > div.simplebar-content > div.ffz--menu-page
[3:25:52] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:25:52] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:25:52] LOG:info | main_menu: Built Tree in 6.85000ms with 126 structure nodes and 196 settings nodes.
[3:25:52] UI | ui.click: span.tw-flex-grow-1
[3:25:52] UI | ui.click: div > div.ffz--home.tw-border-t.tw-pd-y-1 > div > p > a
[3:25:53] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=779416161943853431&instrumentation=%7B%22%2Fv1%2Fhas-app-brtt%22%3A%22160%22%2C%22%2F_r-brtt%22%3A%22211%22%2C%22%2Fv2%2Fevent%2Fcustom-brtt%22%3A%22361%22%7D -> 200
[3:25:53] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:25:53] LOG:info | gql: FollowedChannels [98ms]
    {"variables":{"limit":100,"cursor":""}}
[3:25:53] LOG:info | gql: RecommendedChannels [135ms]
    {"variables":{"first":10,"recID":"a4915fcf-49e6-4321-8b96-1299bf4fcc23","location":"LEFT_NAV","context":{"platform":"web"},"includePromo":false}}
[3:25:53] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:25:53] LOG:info | gql: RealtimeStreamTagList [83ms]
    {"variables":{"channelLogin":"timmy_t5"}}
[3:25:53] LOG:info | gql: updateUserViewedVideo [50ms]
    {"variables":{"input":{"userID":"59576387","position":10835,"videoID":"37979119696","videoType":"LIVE"}}}
[3:25:53] LOG:info | gql: FollowedChannels [95ms]
    {"variables":{"limit":100,"cursor":""}}
[3:25:53] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:25:53] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:25:53] LOG:info | main_menu: Built Tree in 8.83500ms with 126 structure nodes and 196 settings nodes.
[3:25:53] UI | ui.click: span.tw-flex-grow-1

experiments
-------------------------------------------------------------------------------
Unique ID: d422727a97842413

FFZ | New API Stress Testing: true
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: control
TWITCH | paypal_first_v2: control
TWITCH | ABRNetworkLinkFilter: control
TWITCH | twilight_settings_labelling: rest
TWITCH | its_the_remix_to_position: control
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: control
TWITCH | take_the_leaderboard: TakeTop10Spot
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: variant1
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: control
TWITCH | disco_directory_titles: variant1
TWITCH | prowse_li: variant2
TWITCH | disco_max_width: variant1
TWITCH | community-gifting-reduce-friction: control
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | sub_mgmt_modal: variant
TWITCH | TWILIGHT_AAX_DISPLAY: yes
TWITCH | watch_stunt_double: control
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: control
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-b
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | Twilight Player Core NPM Distribution (Public): base
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | ABRObserveredBitrates: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: one_line_no_avatar
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | extension_overlay_improvement: active
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: variant1
TWITCH | liverecs_holdout_device: control
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | channel_level_chat_visibility: control
TWITCH | vxp_mandatory_email_verification: control
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: control
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | watch_stunt_double_user: variant
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: callout_force
TWITCH | abr_fastslow_web: control
TWITCH | twilight_stream_summary_use_kite: no
TWITCH | Devsite_create_apps_form_recaptcha: variant1
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | vxp_thunderdome_logged_in: treatment
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | placement_promotions_pos: control
TWITCH | personalized_sub_modal_p1: visual_benefits
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | vx_onboarding_recs: control
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | vxp_thunderdome_logged_out: treatment
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | subs_pif: gift_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | chat_rejoin_rewrite: variant
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | disabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.11

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: true
chat.lines.alternate: false
chat.lines.padding: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.width: 340
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.tab-complete.emotes-without-colon: false
chat.actions.room-above: false
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.polls: true
chat.points.show-button: true
chat.points.show-rewards: true
chat.emote-menu.sort-emotes: 0
chat.emote-menu.sort-tiers-last: true
chat.actions.room: []
chat.bits.animated: true
theme.tooltips-dark: false
chat.fix-bad-emotes: true
chat.points.auto-rewards: undefined
chat.emote-menu.reduced-padding: false
chat.emote-menu.combine-tabs: false
chat.emote-menu.default-tab: "channel"
chat.emote-menu.show-search: true
chat.emote-menu.show-heading: 1
tooltip.images: true
tooltip.emote-images: true
chat.click-emotes: true
chat.sub-emotes: true
chat.emote-dialogs: true
chat.filtering.highlight-basic-users-blocked: []
chat.filtering.highlight-basic-users-blocked--regex: null
chat.filtering.highlight-basic-badges-blocked: []
chat.filtering.highlight-basic-badges-blocked--list: null
chat.filtering.highlight-basic-blocked: []
chat.filtering.highlight-basic-blocked--regex: null
chat.filtering.highlight-basic-users: []
chat.filtering.highlight-basic-users--color-regex: null
chat.filtering.highlight-basic-badges: []
chat.filtering.highlight-basic-badges--colors: null
chat.filtering.highlight-basic-terms: []
chat.filtering.highlight-basic-terms--color-regex: null
chat.mru.enabled: true
chat.filtering.process-own: false
chat.filtering.display-deleted: false
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.all-links: false
chat.timestamp-format: "h:mm"
chat.badges.hidden: {}
chat.badges.custom-mod: true

**Additional context**

**Comment by GeekBoyMN** [comment] 2020-05-11 01:11
Forgot to mention I even installed FFZ and BTTV in Edge browser on one of the laptops and got the same result as with Chrome and FireFox.

**Comment by SirStendec** [comment] 2020-05-11 22:22
Duplicate of #794

**Closed by SirStendec** 2020-05-11 22:22 UTC
Labels: bug
