### ISSUE TITLE
[Feature Request] Highlight / pin Friend messages in chat

### ISSUE THREAD

**Issue by pyrrhoscliff** [FrankerFaceZ/FrankerFaceZ#116] opened 2017-03-15 21:35 UTC
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
First, thank you for an amazing extension! I was wondering if it were possible to highlight any time a Twitch friend says something in chat.  I know you can highlight keywords in chat, but I didn't see that highlighting base off username was an option. There are times when I am in a large stream with thousands of viewers and I wouldn't mind the ability to highlight comments my friends make so I can see them as the zip by. Or, maybe even have them pin to the top?

Thank you!

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment] 2017-04-02 18:50
Duplicate of #64 / #82

**Closed by SirStendec** 2017-04-02 18:50 UTC
