### ISSUE TITLE
Remove "Duplicate Message" Warning

### ISSUE THREAD

**Issue by CrazyWolf13** [FrankerFaceZ/FrankerFaceZ#1483] opened 2024-04-07 19:26 UTC
**Is your feature request related to a problem? Please describe.**
When sending the same message mutiple times, you cannot send it anymore.
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/96661824/b3214574-0027-47ad-9ea6-86ac3caf4dde)

**Describe the solution you'd like**
Allow sending the same message mutiple times, like other clients do.

**Describe alternatives you've considered**
Using alternatives like chatty or chatterino, but I really don't like their approach.

**Comment by Lordmau5** [comment] 2024-04-07 20:00
Duplicate of https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1202

**Closed by Lordmau5** 2024-04-07 20:00 UTC
Labels: enhancement
