### ISSUE TITLE
[BUG] Sub Tier Badges Textbox Partially Hidden

### ISSUE THREAD

**Issue by Rmac524** [FrankerFaceZ/FrankerFaceZ#152] opened 2017-04-30 13:46 UTC
**Web Browser**: Google Chrome 44

**Do you use BetterTTV or other Twitch extensions**:no

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTkxOQ.log

**Bug / Idea**:
When Channel Bar is on bottom, the textbox that appears when you click the down arrow on the subscribe button is only partially visible.

**Steps to Reproduce (if Applicable)**:
here are my ffz settings in a json file
https://github.com/FrankerFaceZ/FrankerFaceZ/files/965530/ffz-settings.zip

**Comment by SirStendec** [comment] 2017-04-30 17:29
Duplicate of #2. Twitch really needs to learn to position children of things and not absolutely position new elements. And if it does absolutely position things, do a freaking sanity check that they're visible.

Shaking my head.

**Closed by SirStendec** 2017-04-30 17:29 UTC
Labels: bug, duplicate
