### ISSUE TITLE
Blocking a game doesn't hide streams when browsing language-specific list of streams

### ISSUE THREAD

**Issue by mwesolowski1** [FrankerFaceZ/FrankerFaceZ#435] opened 2018-05-03 09:40 UTC
**Web Browser**: Firefox 59.0.3 (64-bit)

**Do you use BetterTTV or other Twitch extensions**: Yes (BetterTTV v7.2.21)

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not Applicable

**Bug / Idea**: Blocking a game doesn't hide streams that play blocked game when browsing language-specific list of streams. However if you click "Hide Thumbnails" it works without any issues. 

**Steps to Reproduce (if Applicable)**:
1. Go to https://www.twitch.tv/directory
2. Set "Show Me" to "Games"
3. Pick any game
4. Click "Block" button
5. Return to https://www.twitch.tv/directory
6. Set "Show Me" to "Channels"
7. Change Twitch language to Polish
8. In the upper section of Twitch where you see "Kanały w języku Polskim" you can still see the games that I've blocked. In this example I've blocked CS: GO, and I can still see streams with that game. However the filtering works in "All channels" section ("Wszystkie kanały" in Polish). See:
![8](https://user-images.githubusercontent.com/8942035/39570031-4ad2ecf0-4ec7-11e8-94d4-c32dbe5099a1.png)

Below are my settings for blocking CS GO

![cs go settings](https://user-images.githubusercontent.com/8942035/39569903-e6498ba4-4ec6-11e8-8674-683446de2feb.png)

**Comment by SirStendec** [comment] 2018-05-03 18:25
I was actually having problems with our query modifications not running on the popular page yesterday. Up-time not displaying and no channel avatars. I was just going to fix it, and I can't seem to reproduce the problem again.

Are you still seeing this or is it fixed for you too? Twitch may have reverted some changes.

**Comment by mwesolowski1** [comment] 2018-05-03 18:42
I actually could not see channel avatars for top 10 streamers with most viewers now. Showing channel uptime in thumbnails worked for me randomly - like 1 time of 10 entries to site https://www.twitch.tv/directory/all
![obraz](https://user-images.githubusercontent.com/8942035/39596361-60a3b6fe-4f12-11e8-8a44-83601869b48f.png)

These are my FrankerFaceZ settings 
![obraz](https://user-images.githubusercontent.com/8942035/39596394-7df53156-4f12-11e8-835b-fcd0c8d1d6ce.png)

**Comment by Lordmau5** [comment] 2019-08-08 02:43
Directory support has been fixed a couple times since this issue was made and from what I can tell this issue is fixed, so I'm gonna go ahead and close this.
If issues like these come up again, don't hesitate to make a new issue :)

**Closed by Lordmau5** 2019-08-08 02:43 UTC
