### ISSUE TITLE
Chat resizing bug since new Twitch UI Update

### ISSUE THREAD

**Issue by cnguyen-de** [FrankerFaceZ/FrankerFaceZ#819] opened 2020-06-12 13:59 UTC
**Describe the bug**
Since the new Twitch UI Update the chat resizing option doesn't work correctly anymore. When you input a number lower than the default width, the content (chat, input field, ...) is still displayed in the default width (container with min-width: 34rem) leading to content being out of view.

**To Reproduce**
1. Set FFZ Setting in Chat > Appearance > Width to a smaller number than the default value, EG: 280
2. Open any stream
3. See chat isn't displayed correctly

**Expected behavior**
The chat's container should be resized and displayed within the resized boundary.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser Chrome
 - Version 83
 - Other Extensions: Ublock Origin, uMatrix, and 20+ more

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
```
initialization
-------------------------------------------------------------------------------
[15:44:25] info | core: FrankerFaceZ v4.19.13 (build 263c67c977aba89432e8 - commit 1c311c89bf800f58942c9141a36da0805cadd400)
[15:44:25] info | settings: Using Provider: LocalStorageProvider
[15:44:25] info | site: Using: Twilight
[15:44:25] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[15:44:25] info | core: Loaded descriptions of 6 modules.
[15:44:25] info | site.fine: Installing MutationObserver.
[15:44:25] info | site: Loaded descriptions of 18 modules.
[15:44:25] info | settings: Initialization complete after 65.21500ms -- Values: 30 -- Profiles: 2
[15:44:25] info | socket: Using Server: wss://pog.frankerfacez.com/
[15:44:25] info | raven: Installed error tracking.
[15:44:25] info | site.switchboard: Found Route and Switch with 22 routes.
[15:44:25] info | site.switchboard: Found Non-Matching Route /activate
[15:44:25] info | site.web_munch: require() grabbed from invocation of module 1vHQ
[15:44:25] info | site.web_munch: require() grabbed in 228.43000ms.
[15:44:25] info | site.web_munch: Loaded names for 468 chunks from require().
[15:44:25] info | site.switchboard: Successfully forced a chunk to load using route /activate
[15:44:25] info | main_menu: Built Tree in 19.71500ms with 126 structure nodes and 195 settings nodes.
[15:44:25] info | main_menu: Built Tree in 10.25500ms with 126 structure nodes and 195 settings nodes.
[15:44:26] info | socket: Connected.
[15:44:26] info | experiments: Loaded information on 1 experiments.
[15:44:26] info | socket: Server Time: 2020-06-12T13:44:26.292Z
[15:44:26] info | socket:  Local Time: 2020-06-12T13:44:26.646Z
[15:44:26] info | socket:   Est. Ping: 250.97000ms
[15:44:26] info | socket: Time Offset: 0.1027529296875
[15:44:26] info | main_menu: Built Tree in 11.10500ms with 126 structure nodes and 195 settings nodes.
[15:44:26] info | core: Initialization complete in 1759.31000ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: "#0E0C13"
theme.color.text: ""
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: 300
chat.use-width: true
layout.use-chat-fix: true
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: true
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 2
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
metadata.host-button: false
channel.metadata.force-above: false
layout.portrait-invert: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: true
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
directory.show-channel-avatars: true
directory.hide-live: false

raven
-------------------------------------------------------------------------------
[11:12:49] LOG:info | null: FrankerFaceZ v4.19.13 (build 263c67c977aba89432e8 - commit 1c311c89bf800f58942c9141a36da0805cadd400)
[11:12:49] LOG:info | settings: Using Provider: LocalStorageProvider
[11:12:49] LOG:info | site: Using: Twilight
[11:12:49] LOG:info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[11:12:49] LOG:info | core: Loaded descriptions of 6 modules.
[11:12:49] LOG:info | site.fine: Installing MutationObserver.
[11:12:49] LOG:info | site: Loaded descriptions of 18 modules.
[11:12:49] LOG:info | settings: Initialization complete after 65.21500ms -- Values: 30 -- Profiles: 2
[11:12:49] LOG:info | socket: Using Server: wss://pog.frankerfacez.com/
[11:12:49] LOG:info | raven: Installed error tracking.
[11:12:49] LOG:info | site.switchboard: Found Route and Switch with 22 routes.
[11:12:49] LOG:info | site.switchboard: Found Non-Matching Route /activate
[11:12:49] HTTP | fetch: GET https://api-test.frankerfacez.com/v2/i18n/locales -> 200
[11:12:49] LOG:info | site.web_munch: require() grabbed from invocation of module 1vHQ
[11:12:49] LOG:info | site.web_munch: require() grabbed in 228.43000ms.
[11:12:49] LOG:info | site.web_munch: Loaded names for 468 chunks from require().
[11:12:49] LOG:info | site.switchboard: Successfully forced a chunk to load using route /activate
[11:12:49] LOG:info | main_menu: Built Tree in 19.71500ms with 126 structure nodes and 195 settings nodes.
[11:12:49] LOG:info | main_menu: Built Tree in 10.25500ms with 126 structure nodes and 195 settings nodes.
[11:12:49] LOG:info | socket: Connected.
[11:12:49] HTTP | fetch: GET https://cdn.frankerfacez.com/script/experiments.json?_=1591969465 -> 200
[11:12:49] HTTP | fetch: GET https://cdn.frankerfacez.com/script/addons.json?_=1591969440 -> 200
[11:12:49] LOG:info | experiments: Loaded information on 1 experiments.
[11:12:49] HTTP | fetch: GET //api.frankerfacez.com/v1/set/global -> 200
[11:12:49] HTTP | fetch: GET //api.frankerfacez.com/v1/badges -> 200
[11:12:49] HTTP | xhr: POST https://api2.branch.io/v1/pageview -> 0
[11:12:49] LOG:info | socket: Server Time: 2020-06-12T13:44:26.292Z
[11:12:49] LOG:info | socket:  Local Time: 2020-06-12T13:44:26.646Z
[11:12:49] LOG:info | socket:   Est. Ping: 250.97000ms
[11:12:49] LOG:info | socket: Time Offset: 0.1027529296875
[11:12:49] LOG:info | main_menu: Built Tree in 11.10500ms with 126 structure nodes and 195 settings nodes.
[11:12:49] LOG:info | core: Initialization complete in 1759.31000ms.
[11:12:49] LOG:info | site.bttv_compat: Sending chat reload event to BetterTTV.
[11:12:49] LOG:info | site.bttv_compat: Sending chat reload event to BetterTTV.
[11:12:49] HTTP | fetch: GET //api.frankerfacez.com/v1/room/id/46622312 -> 200
[11:12:49] LOG:info | chat.emotes: Loaded emote set #3: Global Emotes (11 emotes)
[11:12:49] LOG:info | chat.emotes: Loaded emote set #4330: : Sten's Cheaty Emotes (3 emotes)
[11:12:49] LOG:info | chat.emotes: Added ": Sten's Cheaty Emotes" emote set to 1 users.
[11:12:49] LOG:info | chat.badges: Added "developer" to 2 users.
[11:12:49] LOG:info | chat.badges: Added "bot" to 138 users.
[11:12:49] LOG:info | chat.badges: Added "supporter" to 22671 users.
[11:12:49] LOG:info | chat.badges: Loaded 3 badges and assigned them to 22811 users.
[11:12:49] LOG:info | main_menu: Built Tree in 15.99500ms with 126 structure nodes and 195 settings nodes.
[11:12:49] HTTP | fetch: GET https://cdn.frankerfacez.com/script/emoji/v2-.json?_1591969440 -> 200
[11:12:49] LOG:info | chat.emotes: Loaded emote set #3530: Channel: FrankerFaceZ (0 emotes)
[11:12:49] LOG:info | gql: CoreActionsCurrentUser [43ms]
    {}
[11:12:49] LOG:info | gql: TrackingManager_RequestInfo [3ms]
    {}
[11:12:49] LOG:info | gql: StreamChat [77ms]
    {"variables":{"login":"frankerfacez"}}
[11:12:49] LOG:info | gql: ActiveWatchParty [48ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: ChatList_Badges [55ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: CurrentUserBannedStatus [27ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: ChatInput [83ms]
    {"variables":{"channelLogin":"frankerfacez","isEmbedded":false}}
[11:12:49] LOG:info | gql: Core_Services_Spade_CurrentUser [22ms]
    {}
[11:12:49] LOG:info | chat.emoji: Loaded data about 1568 emoji.
[11:12:49] LOG:info | gql: NewChatterRitual_Channel [40ms]
    {"variables":{"id":"46622312"}}
[11:12:49] LOG:info | gql: GetHypeTrainExecution [39ms]
    {"variables":{"userLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: UseLive [40ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: DropsHighlightService_AvailableDrops [21ms]
    {"variables":{"channelID":"46622312"}}
[11:12:49] LOG:info | gql: EmotePicker_EmotePicker_UserSubscriptionProducts [70ms]
    {"variables":{"channelOwnerID":"46622312"}}
[11:12:49] LOG:info | gql: Chat_ShareBitsBadgeTier_ChannelData [26ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] LOG:info | gql: Chat_ShareResub_ChannelData [62ms]
    {"variables":{"channelLogin":"frankerfacez"}}
[11:12:49] HTTP | fetch: GET https://api.ffzap.com/v1/supporters -> 200
[11:12:49] LOG:info | addon.ffzap-liriklive: Socket: Connecting to socket server...
[11:12:49] HTTP | fetch: GET https://cdn.ffzap.com/liriklive/emotes.json -> 200
[11:12:49] HTTP | xhr: GET https://api.betterttv.net/3/cached/users/twitch/46622312 -> 404
[11:12:49] LOG:info | chat.emotes: Loaded emote set #addon--ffzap.liriklive--emotes-global: Past Emotes (16 emotes)
[11:12:49] LOG:info | chat.emotes: Loaded emote set #addon--ffzap.liriklive--emotes-subscriber: Subscriber Emotes (67 emotes)
[11:12:49] LOG:info | chat.emotes: Loaded emote set #addon--ffzap.liriklive--emotes-restricted: Restricted Emotes (1 emotes)
[11:12:49] LOG:info | main_menu: Built Tree in 17.07000ms with 132 structure nodes and 204 settings nodes.
[11:12:49] LOG:info | gql: ConnectAdIdentityMutation [4ms]
    {"variables":{"input":{"targetDeviceID":"9a78a68938d1e3d8"}}}
[11:12:49] HTTP | xhr: GET https://api.betterttv.net/3/cached/frankerfacez/users/twitch/46622312 -> 200
[11:12:49] LOG:info | addon.ffzap-liriklive: Socket: Connected to socket server.
[11:12:49] UI | ui.click: span.tw-flex-grow-1
[11:12:49] HTTP | fetch: GET https://api.github.com/repos/frankerfacez/frankerfacez/commits -> 200
[11:12:49] UI | ui.click: span.tw-flex-grow-1
[11:12:49] LOG:info | settings: Successfully refreshed 0 of 0 profiles from remote URLs.
[11:12:49] UI | ui.click: span.tw-flex-grow-1
[11:12:49] UI | ui.click: span.tw-flex-grow-1
[11:12:49] UI | ui.click: span.tw-flex-grow-1
[11:12:49] HTTP | fetch: GET https://api.github.com/repos/frankerfacez/frankerfacez/commits -> 200
[11:12:49] UI | ui.click: div.tw-flex__item.tw-flex.tw-flex-nowrap.tw-align-items-center.tw-pd-y-05.tw-pd-r-05

experiments
-------------------------------------------------------------------------------
Unique ID: 9a78a68938d1e3d8

FFZ | New API Stress Testing: false
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: two_lines_with_avatar
TWITCH | paypal_first_v2: control
TWITCH | twilight_settings_labelling: rest
TWITCH | vx_prod_creator_color_cta: control
TWITCH | its_the_remix_to_position: control
TWITCH | emote_good_standing: on
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: variant_fpso_40
TWITCH | take_the_leaderboard: TakeTop10Spot
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: variant1
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: variant
TWITCH | disco_directory_titles: variant1
TWITCH | prowse_li: variant2
TWITCH | disco_max_width: variant1
TWITCH | channel_points_update_indicators_t2: control
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | cg_sku_no_ml_2: control
TWITCH | sub_mgmt_modal: control
TWITCH | TWILIGHT_AAX_DISPLAY: yes
TWITCH | watch_stunt_double: variant
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: treatment
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-b
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | Twilight Player Core NPM Distribution (Public): base
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | why_sub_button: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: two_lines_no_avatar
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | prioritize_paypal_eu: control
TWITCH | secure_checkout: control
TWITCH | extension_overlay_improvement: control
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: variant1
TWITCH | liverecs_holdout_device: control
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | channel_level_chat_visibility: control
TWITCH | vxp_mandatory_email_verification: control
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: control
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | watch_stunt_double_user: variant
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: avatars
TWITCH | twilight_stream_summary_use_kite: no
TWITCH | Devsite_create_apps_form_recaptcha: variant1
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | vxp_thunderdome_logged_in: treatment
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | prioritize_xsolla: variant
TWITCH | placement_promotions_pos: control
TWITCH | personalized_sub_modal_p1: control
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | vx_onboarding_recs: control
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | vxp_thunderdome_logged_out: treatment
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | suggested_tags: sugg_tags
TWITCH | subs_pif: thank_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | chat_rejoin_rewrite: variant
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | enabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | enabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.12

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.ffzap-liriklive

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.emote-menu.sort-emotes: 0
chat.emote-menu.sort-tiers-last: true
chat.fix-bad-emotes: true
chat.actions.room-above: false
chat.actions.room: []
chat.tab-complete.emotes-without-colon: false
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: true
chat.lines.alternate: true
chat.lines.padding: true
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.points.show-button: true
chat.points.show-rewards: true
chat.bits.animated: true
theme.tooltips-dark: false
chat.width: 300
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.badges.custom-mod: true
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.polls: true
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_volume: 50
ffzap.liriklive.global_emoticons: true
ffzap.liriklive.sub_emoticons: true
ffzap.liriklive.gif_emotes_mode: 2
```
**Fix**
The class chat-shell__expanded needs its min-width property removed or set to user's input value

**Comment by brandinarsenault** [comment] 2020-06-13 22:01
Duplicate of #794. Please comment your bug there.

**Closed** 2020-06-23 21:17 UTC
Labels: bug
