### ISSUE TITLE
"Freeze chat scrolling" still not working after 4.0.0-beta1.3@f855394a

### ISSUE THREAD

**Issue by Nightfirecat** [FrankerFaceZ/FrankerFaceZ#296] opened 2017-11-15 19:06 UTC
**Web Browser**: Firefox 57.0

**Do you use BetterTTV or other Twitch extensions**: Yes (but might not work with new Twitch?); The FrankerFacez Addon Pack, via GreaseMonkey

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: When chat is set to freeze on hover, it still scrolls normally. (I believe it was working before today, though the background striping changed colors as chat messages were added)

**Steps to Reproduce (if Applicable)**: Set chat to freeze on hover and move mouse over chat.

**Comment by SirStendec** [comment] 2017-11-15 19:09
Duplicate of #295

**Closed by SirStendec** 2017-11-15 19:09 UTC
Labels: bug, duplicate

**Comment by Nightfirecat** [comment] 2017-11-15 22:15
Unless I misunderstood, I don't think it is a duplicate. I'll do some testing after work (against a clean profile) and see if I can get a clearer set of repro steps and a gif of the behavior.

**Comment by SirStendec** [comment] 2017-11-15 22:26
I'd like all further comments about chat scrolling issues to go to #298 for now.
