### ISSUE TITLE
Hide Thumbnails Not Working

### ISSUE THREAD

**Issue by caerulius** [FrankerFaceZ/FrankerFaceZ#770] opened 2020-03-19 17:51 UTC
To Reproduce: Select a game to hide the thumbnails for, return to your following page, refresh. The thumbnail is still visible.

OS: Windows
Browser: 80.0.3987.149

**Comment by SirStendec** [comment] 2020-03-22 16:23
Duplicate of #765 (same problem causing both)

**Closed by SirStendec** 2020-03-22 16:23 UTC
