### ISSUE TITLE
"Highlight my message" doesn't work since recently

### ISSUE THREAD

**Issue by TheRobbebas** [FrankerFaceZ/FrankerFaceZ#821] opened 2020-06-13 21:28 UTC
**Describe the bug**
When someone, be it me or another user, redeems Highlight my message, it doesn't do anything special to the message anymore. No purple border and no yellow colour.

**To Reproduce**
1. Redeem "Highlight my message" and send a message
2. See the error

**Expected behavior**
I expect the Highlighted message to appear with a yellow background or a purple marking, like it used to about 2 weeks ago.

**Screenshots**
How the message looks with FFZ: https://i.imgur.com/mPwb3QA.png
How the message looks in an incognito tab with no FFZ: https://i.imgur.com/xmjGfXq.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97
 - Other Extensions: uBlock, Privacy Badger, BetterTTV, Enhancer for Youtube, RES, HTTPS Everywhere, Dropbox for Gmail, SteamDB

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
```
initialization
-------------------------------------------------------------------------------
[23:19:47] info | core: FrankerFaceZ v4.19.13 (build 263c67c977aba89432e8 - commit 1c311c89bf800f58942c9141a36da0805cadd400)
[23:19:47] info | settings: Using Provider: LocalStorageProvider
[23:19:47] info | site: Using: Twilight
[23:19:47] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[23:19:47] info | core: Loaded descriptions of 6 modules.
[23:19:47] info | site.fine: Installing MutationObserver.
[23:19:47] info | site: Loaded descriptions of 18 modules.
[23:19:48] info | settings: Initialization complete after 196.40500ms -- Values: 5 -- Profiles: 2
[23:19:48] info | socket: Using Server: wss://andknuckles.frankerfacez.com/
[23:19:48] info | raven: Installed error tracking.
[23:19:48] info | site.switchboard: Found Route and Switch with 11 routes.
[23:19:48] info | site.switchboard: Found Non-Matching Route /event/:teamName
[23:19:48] warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: Cannot read property 'match' of undefined
[23:19:48] info | site.switchboard: Found Non-Matching Route /partner/signup
[23:19:48] info | main_menu: Built Tree in 36.92000ms with 126 structure nodes and 195 settings nodes.
[23:19:48] info | site.web_munch: require() grabbed from invocation of module uHYy
[23:19:48] info | site.web_munch: require() grabbed in 1064.23000ms.
[23:19:48] info | site.web_munch: Loaded names for 468 chunks from require().
[23:19:48] info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[23:19:49] info | experiments: Loaded information on 1 experiments.
[23:19:49] info | core: Initialization complete in 1558.34500ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
chat.bits.show: true
layout.display-bits-button: true
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: 340
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
channel.metadata.force-above: false
layout.portrait-invert: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 5
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
directory.show-channel-avatars: true
directory.hide-live: false
ffz.show-new-settings: true
player.no-autoplay: false
player.home.autoplay: true
player.button.pip: true
player.button.reset: true
player.compressor.enable: true
player.allow-catchup: true
player.compressor.default: false
reports.error.enable: true
reports.error.include-settings: true
reports.error.include-user: false

raven
-------------------------------------------------------------------------------
[11:14:43] LOG:info | null: FrankerFaceZ v4.19.13 (build 263c67c977aba89432e8 - commit 1c311c89bf800f58942c9141a36da0805cadd400)
[11:14:43] LOG:info | settings: Using Provider: LocalStorageProvider
[11:14:43] LOG:info | site: Using: Twilight
[11:14:43] LOG:info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[11:14:43] LOG:info | core: Loaded descriptions of 6 modules.
[11:14:43] LOG:info | site.fine: Installing MutationObserver.
[11:14:43] LOG:info | site: Loaded descriptions of 18 modules.
[11:14:43] LOG:info | settings: Initialization complete after 196.40500ms -- Values: 5 -- Profiles: 2
[11:14:43] LOG:info | socket: Using Server: wss://andknuckles.frankerfacez.com/
[11:14:43] LOG:info | raven: Installed error tracking.
[11:14:43] LOG:info | site.switchboard: Found Route and Switch with 11 routes.
[11:14:43] LOG:info | site.switchboard: Found Non-Matching Route /event/:teamName
[11:14:43] LOG:warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: Cannot read property 'match' of undefined
[11:14:43] LOG:info | site.switchboard: Found Non-Matching Route /partner/signup
[11:14:43] UI | ui.click: img.tw-block.tw-border-radius-rounded.tw-image.tw-image-avatar[alt="User Avatar"]
[11:14:43] LOG:info | main_menu: Built Tree in 36.92000ms with 126 structure nodes and 195 settings nodes.
[11:14:43] LOG:info | site.web_munch: require() grabbed from invocation of module uHYy
[11:14:43] LOG:info | site.web_munch: require() grabbed in 1064.23000ms.
[11:14:43] LOG:info | site.web_munch: Loaded names for 468 chunks from require().
[11:14:43] LOG:info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[11:14:43] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[11:14:43] HTTP | fetch: GET https://cdn.frankerfacez.com/script/experiments.json?_=1592083185 -> 200
[11:14:43] HTTP | fetch: GET https://cdn.frankerfacez.com/script/addons.json?_=1592083170 -> 200
[11:14:43] LOG:info | experiments: Loaded information on 1 experiments.
[11:14:43] LOG:info | core: Initialization complete in 1558.34500ms.
[11:14:43] HTTP | fetch: GET //api.frankerfacez.com/v1/badges -> 200
[11:14:43] HTTP | fetch: GET //api.frankerfacez.com/v1/set/global -> 200
[11:14:43] HTTP | fetch: GET https://cdn.frankerfacez.com/script/emoji/v2-.json?_1592083140 -> 200
[11:14:43] LOG:info | chat.badges: Added "developer" to 2 users.
[11:14:43] LOG:info | chat.badges: Added "bot" to 138 users.
[11:14:43] LOG:info | chat.badges: Added "supporter" to 22719 users.
[11:14:43] LOG:info | chat.badges: Loaded 3 badges and assigned them to 22859 users.
[11:14:43] LOG:info | chat.emotes: Loaded emote set #3: Global Emotes (11 emotes)
[11:14:43] LOG:info | chat.emotes: Loaded emote set #4330: : Sten's Cheaty Emotes (3 emotes)
[11:14:43] LOG:info | chat.emotes: Added ": Sten's Cheaty Emotes" emote set to 1 users.
[11:14:43] LOG:info | chat.emoji: Loaded data about 1568 emoji.
[11:14:43] LOG:info | gql: EmailVerificationSuccess [21ms]
    {}
[11:14:43] LOG:info | gql: VerifyEmail_CurrentUser [26ms]
    {}
[11:14:43] LOG:info | gql: ProvideEmail_CurrentUser [26ms]
    {}
[11:14:43] LOG:info | gql: Whispers_Whispers_UserWhisperThreads [62ms]
    {"variables":{}}
[11:14:43] LOG:info | gql: ConnectAdIdentityMutation [3ms]
    {"variables":{"input":{"targetDeviceID":"8vVBUmiFoTrxj6uF1JkGxHcrf4fkU6Pf"}}}
[11:14:43] LOG:info | gql: PlayerTrackingContextQuery [59ms]
    {"variables":{"channel":"twitchgaming","isLive":true,"hasCollection":false,"collectionID":"","videoID":"","hasVideo":false,"slug":"","hasClip":false}}
[11:14:43] LOG:info | gql: ExtensionsUIContext_ChannelID [20ms]
    {"variables":{"channelLogin":"twitchgaming"}}
[11:14:43] LOG:info | gql: ExtensionsForChannelCurrentUser [2ms]
    {"variables":{"channelID":""}}
[11:14:43] LOG:info | gql: VideoPreviewOverlay [57ms]
    {"variables":{"login":"twitchgaming"}}
[11:14:43] LOG:info | gql: VideoAdBanner [38ms]
    {"variables":{"isLive":true,"isVOD":false,"isCollection":false,"login":"twitchgaming","vodID":"","collectionID":""}}
[11:14:43] LOG:info | gql: VideoPlayerClipsButtonChannel [40ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] LOG:info | gql: MatureGateOverlayChannel [44ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] LOG:info | gql: VideoPlayer_AgeGateOverlayChannel [42ms]
    {"variables":{"channelLogin":"twitchgaming"}}
[11:14:43] LOG:info | gql: CountessData [20ms]
    {"variables":{"channelLogin":"twitchgaming"}}
[11:14:43] LOG:info | gql: VideoPlayer_VideoSourceManager [20ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] LOG:info | gql: VideoPlayerPixelAnalyticsUrls [51ms]
    {"variables":{"login":"twitchgaming","allowAmazon":true,"allowComscore":true,"allowGoogle":true,"allowNielsen":true}}
[11:14:43] LOG:info | gql: ComscoreStreamingQuery [57ms]
    {"variables":{"channel":"twitchgaming","clipSlug":"","isClip":false,"isLive":true,"isVodOrCollection":false,"vodID":""}}
[11:14:43] LOG:info | gql: StreamRefetchManager [40ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] LOG:info | gql: VideoAdRequestHandling [75ms]
    {"variables":{"isLive":true,"login":"twitchgaming","isVOD":false,"vodID":"","isCollection":false,"collectionID":""}}
[11:14:43] LOG:info | gql: NielsenContentMetadata [57ms]
    {"variables":{"isCollectionContent":false,"isLiveContent":true,"isVODContent":false,"collectionID":"","login":"twitchgaming","vodID":""}}
[11:14:43] LOG:info | gql: VideoPlayerStreamMetadata [40ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] HTTP | fetch: GET https://api.twitch.tv/api/channels/twitchgaming/access_token?need_https=true&oauth_token=REDACTED&platform=web&player_backend=mediaplayer&player_type=frontpage -> 200
[11:14:43] HTTP | fetch: GET https://api.twitch.tv/v5/channels/527115020/extensions -> 200
[11:14:43] LOG:info | gql: ExtensionsForChannelCurrentUser [23ms]
    {"variables":{"channelID":"527115020"}}
[11:14:43] LOG:info | gql: StreamRefetchManager [40ms]
    {"variables":{"channel":"twitchgaming"}}
[11:14:43] HTTP | fetch: GET https://api-test.frankerfacez.com/v2/i18n/locales -> 200
[11:14:43] LOG:info | gql: VideoAdRequestDecline [5ms]
    {"variables":{"context":{"adSessionID":"0em18LksQNQdt5ub9V1X14OgreMA90","clientContext":{"isAudioOnly":false,"isMiniTheater":false,"isPIP":false,"isUsingExternalPlayback":false},"duration":30,"playerContext":{"contentType":"LIVE","isAutoPlay":true,"nauthSig":"99e81d22cf6cb428ff6b56046bac818be594eff8","nauthToken":"{\"adblock\":true,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"twitchgaming\",\"channel_id\":527115020,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924905600},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"8vVBUmiFoTrxj6uF1JkGxHcrf4fkU6Pf\",\"expires\":1592084390,\"extended_history_allowed\":false,\"game\":\"Summer Game Fest\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"_\",\"player_type\":\"frontpage\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"server_ads\":false,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":52040676,\"user_ip\":\"94.224.156.202\",\"version\":2}"},"rollType":"PREROLL"}}}
[11:14:43] LOG:info | socket: Connected.
[11:14:43] LOG:info | gql: VideoAdRequestDecline [4ms]
    {"variables":{"context":{"adSessionID":"UXahnB1PVYfV5gR1yIvwqhmpbjTHUE","clientContext":{"isAudioOnly":false,"isMiniTheater":false,"isPIP":false,"isUsingExternalPlayback":false},"duration":30,"playerContext":{"contentType":"LIVE","isAutoPlay":true,"nauthSig":"99e81d22cf6cb428ff6b56046bac818be594eff8","nauthToken":"{\"adblock\":true,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"twitchgaming\",\"channel_id\":527115020,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924905600},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"8vVBUmiFoTrxj6uF1JkGxHcrf4fkU6Pf\",\"expires\":1592084390,\"extended_history_allowed\":false,\"game\":\"Summer Game Fest\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"_\",\"player_type\":\"frontpage\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"server_ads\":false,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":52040676,\"user_ip\":\"94.224.156.202\",\"version\":2}"},"rollType":"PREROLL"}}}
[11:14:43] LOG:info | settings: Successfully refreshed 0 of 0 profiles from remote URLs.
[11:14:43] LOG:info | socket: Server Time: 2020-06-13T21:19:53.541Z
[11:14:43] LOG:info | socket:  Local Time: 2020-06-13T21:19:53.441Z
[11:14:43] LOG:info | socket:   Est. Ping: 346.64250ms
[11:14:43] LOG:info | socket: Time Offset: -0.446767578125
[11:14:43] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[11:14:43] LOG:info | main_menu: Built Tree in 12.68500ms with 126 structure nodes and 195 settings nodes.
[11:14:43] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[11:14:43] UI | ui.click: span.tw-flex-grow-1
[11:14:43] LOG:info | gql: updateUserViewedVideo [40ms]
    {"variables":{"input":{"userID":"52040676","position":21149,"videoID":"38652393792","videoType":"LIVE"}}}
[11:14:43] LOG:info | socket: Disconnected. (1006:)
[11:14:43] LOG:info | socket: Using Server: wss://andknuckles.frankerfacez.com/
[11:14:43] LOG:info | socket: Connected.
[11:14:43] LOG:info | socket: Server Time: 2020-06-13T21:23:31.447Z
[11:14:43] LOG:info | socket:  Local Time: 2020-06-13T21:23:31.344Z
[11:14:43] LOG:info | socket:   Est. Ping: 476.32250ms
[11:14:43] LOG:info | socket: Time Offset: -0.579842529296875
[11:14:43] UI | ui.click: div.tw-flex__item.tw-flex.tw-flex-nowrap.tw-align-items-center.tw-pd-y-05.tw-pd-r-05

experiments
-------------------------------------------------------------------------------
Unique ID: 8vVBUmiFoTrxj6uF1JkGxHcrf4fkU6Pf

FFZ | New API Stress Testing: false
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: one_line_no_avatar
TWITCH | paypal_first_v2: control
TWITCH | ABRNetworkLinkFilter: control
TWITCH | twilight_settings_labelling: rest
TWITCH | player_core_ad_loudness: control
TWITCH | vx_prod_creator_color_cta: control
TWITCH | its_the_remix_to_position: control
TWITCH | emote_good_standing: on
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: control
TWITCH | take_the_leaderboard: Control
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: variant1
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: control
TWITCH | disco_directory_titles: variant1
TWITCH | prowse_li: variant2
TWITCH | disco_max_width: variant1
TWITCH | channel_points_update_indicators_t2: control
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | cg_sku_no_ml_2: control
TWITCH | sub_mgmt_modal: control
TWITCH | TWILIGHT_AAX_DISPLAY: yes
TWITCH | watch_stunt_double: variant
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: treatment
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-b
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | Twilight Player Core NPM Distribution (Public): variant-b
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | ABRObserveredBitrates: control
TWITCH | why_sub_button: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: one_line_no_avatar
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | prioritize_paypal_eu: control
TWITCH | secure_checkout: control
TWITCH | extension_overlay_improvement: active
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: control
TWITCH | liverecs_holdout_device: holdout
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | channel_level_chat_visibility: control
TWITCH | vxp_mandatory_email_verification: control
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: bits_landing_page_new_copy
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | watch_stunt_double_user: variant
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: control
TWITCH | abr_fastslow_web: control
TWITCH | twilight_stream_summary_use_kite: no
TWITCH | Devsite_create_apps_form_recaptcha: control
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | vxp_thunderdome_logged_in: treatment
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | prioritize_xsolla: control
TWITCH | placement_promotions_pos: control
TWITCH | personalized_sub_modal_p1: control
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | vx_onboarding_recs: control
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | vxp_thunderdome_logged_out: treatment
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | suggested_tags: control
TWITCH | subs_pif: thank_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | chat_rejoin_rewrite: variant
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | disabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.12

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: false
chat.lines.alternate: true
chat.lines.padding: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.width: 340
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""
```

**Comment by brandinarsenault** [comment] 2020-06-13 22:01
Duplicate of #794. Please comment your bug there.

**Closed** 2020-06-23 21:17 UTC
Labels: bug
