### ISSUE TITLE
Directory > Channels Settings not working

### ISSUE THREAD

**Issue by Zwangi** [FrankerFaceZ/FrankerFaceZ#778] opened 2020-04-03 06:41 UTC
**Describe the bug**
If checking the "Do not show reruns in the directory." box, no changes are happening.
Also Hide "LIVE" and display Channel Avatars have no effect

**To Reproduce**
1. Go to "https://www.twitch.tv/directory/following" and Open FFZ settings.
2. Navigate to Directory and Channels in the FFZ overlay
3. Check "Do not show reruns in the directory." (or any setting for this category)
4. See nothing happen, even on reloading the page

**Expected behavior**
The Rerun "preview" Image of the stream should not be visible anymore.

**Screenshots**
https://i.imgur.com/sU7vGTa.png

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: issue appears in Chrome and the Chrome based 'Brave' Browser
 - Version:
Chrome: Version 80.0.3987.163 (Official Build) (64-Bit)
Brave: Version 1.5.122 Chromium: 80.0.3987.162 (Official Build) (64-bit)

 - Other Extensions: ffz addon pack on brave and just FFZ on chrome

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
`initialization
-------------------------------------------------------------------------------
[8:10:08] info | core: FrankerFaceZ v4.19.5 (build 48a8ff6f5dfc8c465c3d - commit 99eee7396d7b40a0ba3bea50ab3133595c6e5dae)
[8:10:08] info | settings: Using Provider: LocalStorageProvider
[8:10:08] info | site: Using: Twilight
[8:10:08] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[8:10:08] info | core: Loaded descriptions of 6 modules.
[8:10:08] info | site.fine: Installing MutationObserver.
[8:10:08] info | site: Loaded descriptions of 18 modules.
[8:10:08] info | settings: Initialization complete after 20.71000ms -- Values: 60 -- Profiles: 1
[8:10:08] info | socket: Using Server: wss://champ.frankerfacez.com/
[8:10:08] info | raven: Installed error tracking.
[8:10:08] info | site.switchboard: Found Route and Switch with 13 routes.
[8:10:08] info | site.switchboard: Found Non-Matching Route /event/:teamName
[8:10:08] warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: Cannot read property 'match' of undefined
[8:10:08] info | site.switchboard: Found Non-Matching Route /partner/signup
[8:10:08] info | site.web_munch: Twitch Chunk Loaded: 237 (237)
[8:10:08] info | site.web_munch: require() grabbed from invocation of module uHYy
[8:10:08] info | site.web_munch: require() grabbed in 28.57500ms.
[8:10:08] info | site.web_munch: Loaded names for 432 chunks from require().
[8:10:08] info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[8:10:08] info | site.fine: Found class for "nav-cards" at depth 22
[8:10:08] info | main_menu: Built Tree in 10.21500ms with 126 structure nodes and 195 settings nodes.
[8:10:09] info | site.fine: Found class for "nav-bar" at depth 59
[8:10:09] info | site.fine: Found class for "bits-button" at depth 80
[8:10:09] info | main_menu: Built Tree in 5.57500ms with 130 structure nodes and 201 settings nodes.
[8:10:09] info | socket: Connected.
[8:10:09] info | experiments: Loaded information on 1 experiments.
[8:10:09] warn | site.player: Unable to install document visibility hook. TypeError: Cannot redefine property: hidden
[8:10:09] info | core: Initialization complete in 1717.30500ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
chat.bits.show: false
layout.display-bits-button: false
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.side-nav.hide-offline: true
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 0
layout.side-nav.show-friends: 1
whispers.show: true
layout.theme.global-font: ""
channel.metadata.force-above: true
layout.portrait-invert: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
directory.show-channel-avatars: false
directory.hide-live: true
ffz.show-new-settings: true
chat.width: 340
chat.use-width: false
directory.hide-recommended: false
directory.hide-vodcasts: true
directory.uptime: 1

raven
-------------------------------------------------------------------------------
[9:31:34] LOG:info | site.fine: Found class for "directory-shelf" at depth 113
[9:31:34] LOG:info | chat.emoji: Loaded data about 1568 emoji.
[9:31:34] LOG:info | gql: EmailVerificationSuccess [22ms]
    {}
[9:31:34] LOG:info | gql: VerifyEmail_CurrentUser [25ms]
    {}
[9:31:34] LOG:info | gql: ProvideEmail_CurrentUser [24ms]
    {}
[9:31:34] LOG:info | gql: Whispers_Whispers_UserWhisperThreads [76ms]
    {"variables":{}}
[9:31:34] LOG:info | settings: Successfully refreshed 0 of 0 profiles from remote URLs.
[9:31:34] LOG:info | gql: Prime_PrimeOfferList_PrimeOffers [199ms]
    {"variables":{}}
[9:31:34] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[9:31:34] LOG:info | main_menu: Built Tree in 5.25000ms with 130 structure nodes and 201 settings nodes.
[9:31:34] UI | ui.click: div.tw-flex__item.tw-flex.tw-flex-nowrap.tw-align-items-center.tw-pd-y-05.tw-pd-r-05
[9:31:34] HTTP | fetch: GET https://api.github.com/repos/frankerfacez/frankerfacez/commits -> 200
[9:31:34] UI | ui.click: input#ffz-main-menu.search.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-input.tw-pd-l-3.tw-pd-r-1.tw-pd-y-05[type="search"]
[9:31:34] UI | ui.input: input#ffz-main-menu.search.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-input.tw-pd-l-3.tw-pd-r-1.tw-pd-y-05[type="search"]
[9:31:34] UI | ui.input: input#ffz-main-menu.search.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-input.tw-pd-l-3.tw-pd-r-1.tw-pd-y-05[type="search"]
[9:31:34] UI | ui.click: span.tw-flex-grow-1
[9:31:34] UI | ui.click: select#setting:layout.side-nav.rerun-style.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:34] UI | ui.click: select#setting:layout.side-nav.rerun-style.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:34] UI | ui.click: select#setting:layout.side-nav.rerun-style.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:34] UI | ui.click: select#setting:layout.side-nav.rerun-style.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:34] UI | ui.click: span.tw-flex-grow-1
[9:31:34] UI | ui.click: label.tw-checkbox__label > span.tw-mg-l-1
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:34] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:34] LOG:info | site.compat_emote_menu: Emote Menu for Twitch was not found after 60 seconds.
[9:31:34] UI | ui.click: div.tw-c-text-alt-2 > a.tw-link.tw-link--inherit
[9:31:34] LOG:info | gql: FollowedChannels [122ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:34] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[9:31:34] LOG:info | gql: FollowedChannels [95ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:34] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[9:31:34] LOG:info | gql: RecommendedChannels [133ms]
    {"variables":{"first":10,"recID":"1ec5cfc5-3c93-4501-9128-cdf6275def3a","location":"LEFT_NAV","context":{"platform":"web"},"includePromo":false}}
[9:31:35] LOG:info | gql: FollowedChannels [100ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:35] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[9:31:35] UI | ui.click: div.ffz--widget.ffz--checkbox > div.tw-flex.tw-align-items-center.tw-checkbox
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.hide-live.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.simplebar-content > div.ffz--menu-page > header.tw-mg-b-1
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: select#setting:directory.uptime.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:35] UI | ui.click: select#setting:directory.uptime.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:35] LOG:info | gql: FollowedChannels [106ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:35] UI | ui.click: select#setting:directory.uptime.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:35] UI | ui.click: select#setting:directory.uptime.tw-border-radius-medium.tw-font-size-6.tw-select.tw-pd-l-1.tw-pd-r-3.tw-pd-y-05.tw-mg-05
[9:31:35] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[9:31:35] LOG:info | gql: RecommendedChannels [135ms]
    {"variables":{"first":10,"recID":"4da0007a-46e9-4f76-9382-391000f853af","location":"LEFT_NAV","context":{"platform":"web"},"includePromo":false}}
[9:31:35] LOG:info | gql: FollowedChannels [108ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.hide-vodcasts.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: span.tw-button__text.ffz-i-cancel
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.show-channel-avatars.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: div.simplebar-scroll-content > div.simplebar-content
[9:31:35] UI | ui.click: label.tw-checkbox__label > span.tw-mg-l-1
[9:31:35] UI | ui.click: input#setting:directory.hide-live.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: label.tw-checkbox__label > span.tw-mg-l-1
[9:31:35] UI | ui.click: input#setting:directory.hide-live.tw-checkbox__input[type="checkbox"]
[9:31:35] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] UI | ui.click: div.tw-flex.tw-align-items-center.tw-checkbox > label.tw-checkbox__label
[9:31:35] UI | ui.click: input#setting:directory.hide-live.tw-checkbox__input[type="checkbox"]
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] LOG:info | gql: FollowedChannels [108ms]
    {"variables":{"limit":100,"cursor":""}}
[9:31:35] UI | ui.click: header.tw-c-background-base.tw-full-width.tw-align-items-center.tw-flex.tw-flex-nowrap
[9:31:35] UI | ui.click: div > div.ffz--widget.ffz--select-box > div.tw-flex.tw-align-items-center
[9:31:35] UI | ui.click: span.tw-flex-grow-1
[9:31:35] UI | ui.click: span.tw-flex-grow-1

experiments
-------------------------------------------------------------------------------
Unique ID: 883f65e377cf9fc5

FFZ | New API Stress Testing: true
TWITCH | vx_aa_logged_out: control_b
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: control
TWITCH | paypal_first_v2: control
TWITCH | ABRNetworkLinkFilter: control
TWITCH | twilight_settings_labelling: rest
TWITCH | its_the_remix_to_position: control
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | missing_boxart: control
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: control
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | vx_aa_logged_in: control_b
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: variant1
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: control
TWITCH | disco_directory_titles: variant1
TWITCH | prowse_li: variant2
TWITCH | disco_max_width: variant1
TWITCH | chat_command_autocomplete_v2: variant1
TWITCH | vxp_thunderdome: control
TWITCH | community-gifting-reduce-friction: control
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | vx_aa_all: control_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | sub_mgmt_modal: control
TWITCH | TWILIGHT_AAX_DISPLAY: yes
TWITCH | watch_stunt_double: control
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: control
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-a
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | chat_input_revamp: variant1
TWITCH | Twilight Player Core NPM Distribution (Public): variant-a
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | ABRObserveredBitrates: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: control
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | fpso: control
TWITCH | extension_overlay_improvement: control
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | ad_affiliate_rev_share: treatment
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: control
TWITCH | liverecs_holdout_device: control
TWITCH | featured_carousel_avatars: control
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | vxp_mandatory_email_verification: variant
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: bits_landing_page_new_copy
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: control
TWITCH | abr_fastslow_web: control
TWITCH | Devsite_create_apps_form_recaptcha: control
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | placement_promotions_pos: control
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | subs_pif: thank_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | enabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.8

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffzap-core

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_volume: 50
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 1
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.filtering.deleted-style: 0
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: false
chat.bits.show-pinned: false
chat.lines.alternate: true
chat.lines.padding: true
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 1
chat.width: 340
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""`
**Additional context**
stoped working ~ 1 month ago.
Tried loading configs and resetting all ffz and also browser settings
Fresh installed browsers got the same issue

**Comment by SirStendec** [comment] 2020-04-03 21:01
Duplicate of #765

**Closed by SirStendec** 2020-04-03 21:01 UTC
Labels: bug
