### ISSUE TITLE
Automatic Theater Mode doesn't force Theater Mode when loading a channel from the following page

### ISSUE THREAD

**Issue by dirkened** [FrankerFaceZ/FrankerFaceZ#35] opened 2016-10-10 23:07 UTC
**Web Browser**:

Reproduced on:
Mozilla Nightly v52.0a1
Google Chrome v53.0.2785 m

**Do you use BetterTTV or other Twitch extensions**:

I use the extension BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

Found Twitch application after 0 ms at: https://www.twitch.tv/jacobrl
Initializing FrankerFaceZ version 3.5.319
Loading settings.
Error loading value for "twitch_chat_dark": SyntaxError: Unexpected token u in JSON at position 0
Injecting FrankerFaceZ Dark Twitch CSS.
Injecting main FrankerFaceZ CSS.
Readying toggleable styles.
Installing mouse-up event to auto-close pop-ups.
Using Socket Server: wss://andknuckles.frankerfacez.com/ [1:1]
Preparing emoticon system.
Creating emoticon style element.
Loading global emote sets.
Loading emoji data.
Watching Twitch emoticon parser to ensure it loads.
Preparing badge system.
Creating badge style element.
Generating CSS for existing Twitch badges.
Loading badges.
Hooking the Ember router.
Hooking Ember chat line helpers.
Creating channel style element.
Hooking the Ember Channel Index redesign.
Hooking the Ember Channel controller.
Creating room style element.
Hooking the Ember Chat PubSub service.
Hooking the Ember Room controller.
Hooking the Ember Room model.
Adding Room: jacobrl
Hooking the Ember Room view.
Creating layout style element.
Hooking the Ember service:layout
Hooking the Ember Chat controller.
Hooking the Ember Chat view.
Hooking the Ember from-display-preview component.
Listening to the Settings controller to catch mod icon state changes.
Modifying Mousetrap stopCallback so we can catch ESC.
Hooking the Ember Moderation Card view.
Hooking the Ember Chat Input component.
Hooking the Ember Directory views.
Updating Ember classes and instances.
Updated 0 existing instances across 1 classes.
Attempting to modify the Following collection.
Hooking the Ember games-following controller.
Adding event handler for window focus.
Initializing following support.
Connecting to Live Streams model.
Initializing race support.
Updating Ember classes and instances.
There was an error creating and destroying an instance of the Ember class "component:twitch-player2" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:channel-redesign" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:channel-redesign/live" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:vod-chat-display" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:twitch-conversations/conversation-window" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:twitch-conversations/conversation-settings-menu" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:twitch-profile-card" to clear its cache.
There was an error creating and destroying an instance of the Ember class "component:channel-feed/comment" to clear its cache.
Updated 7 existing instances across 29 classes.
Modifying Tipsy-Tooltip component to use gravity.
Fixing already existing tooltips.
Adding Room: dirkened
Listening for Window Messages.
Checking for Feature Friday data...
Initialization complete in 138.64499999999998ms
Updated emoticons for set #3: Global Emoticons
Updated emoticons for set #4330: : Sten's Cheaty Emotes
Added ": Sten's Cheaty Emotes" emote set to 1 users.
Loaded data on 1601 emoji.
Added "developer" badge to 2 users.
Added "bot" badge to 101 users.
Added "supporter" badge to 5,005 users.
Loaded 5,108 total badges across 3 types.
Updated emoticons for set #51050: Channel: dirkened
Socket Connected.
Adding Room: _frankerfacez_1403583234092
Registered New Extension #0: BetterTTV
Ext "BetterTTV": Injected successfully.
Ext "BetterTTV": SocketClient: Connecting to Beta BetterTTV Socket Server
Error Saying Hello: Error: Expected array of string, string as arguments.
Socket Reply to 2 - SUCCESS -- undefined
Socket Reply to 3 - SUCCESS -- undefined
Socket Reply to 4 - SUCCESS -- undefined
Socket Reply to 7 - SUCCESS -- undefined
Updated emoticons for set #3850: Group Chat: FFZ Donor Lounge
Socket Reply to 9 - SUCCESS -- undefined
Ext "BetterTTV": Adding badge 'emotes' for user 'jorkauf'.
Ext "BetterTTV": Adding badge 'emotes' for user 'wolfyy'.
Ext "BetterTTV": Adding badge 'emotes' for user 'stun_empire'.
Ext "BetterTTV": Adding badge 'emotes' for user 'crusader'.
Ext "BetterTTV": Adding badge 'emotes' for user 'shadowbandit001'.
Ext "BetterTTV": Adding badge 'emotes' for user 'brutal_melo'.
Ext "BetterTTV": Adding badge 'emotes' for user 'nightmare'.
Ext "BetterTTV": Adding badge 'emotes' for user 'character'.
Ext "BetterTTV": Adding badge 'emotes' for user 'sorty96'.
Ext "BetterTTV": Adding badge 'design' for user 'jacksack'.
Ext "BetterTTV": Adding badge 'design' for user 'julia'.
Ext "BetterTTV": Adding badge 'support' for user 'siikrick'.
Ext "BetterTTV": Adding badge 'support' for user 'aaron128l'.
Ext "BetterTTV": Adding badge 'developer' for user 'polecat'.
Ext "BetterTTV": Adding badge 'developer' for user 'teak'.
Ext "BetterTTV": Adding badge 'developer' for user 'ehsankia'.
Ext "BetterTTV": Adding badge 'developer' for user 'dtittel'.
Ext "BetterTTV": Adding badge 'developer' for user 'night'.
Ext "BetterTTV": Loaded Emoticon Set #9001: Emoticons (GIF) (5 emotes)
Ext "BetterTTV": Loaded Emoticon Set #9003: Emoticons (GIF) (1 emotes)
Ext "BetterTTV": SocketClient: Connected to Beta BetterTTV Socket Server
Ext "BetterTTV": Loaded Emoticon Set #1: Global Emoticons (89 emotes)
Ext "BetterTTV": Loaded Emoticon Set #2: Global Emoticons (GIF) (1 emotes)
Ext "BetterTTV": Loaded Emoticon Set #3: Global Emoticons (Override) (2 emotes)
Player Pause State for jacobrl: false
Error: There was an error within an Ember RSVP. [undefined]
BetterTTV was not detected after 60 seconds.
Emote Menu for Twitch was not detected after 60 seconds.
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #tha_gary_images: Personal Emotes (5 emotes)
Error: There was an unknown error within Ember. [TypeError: Cannot read property 'set' of null]
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #mrgamezombie1_images: Personal Emotes (5 emotes)
Changed Setting "advanced_settings" to: true
Changed Setting "advanced_settings" to: true
Changed Setting "keywords" to: ["regex: [d]s?([il1o0öuü]s?){1,7}[r]s?[k]s?[e3]s?[n]s?[e3]s?[d]","regex: [d]s?[il1o0öuü]s?[rR]s?[k]s?[e3]s?[n]s?[e3]s?[d]","regex: [d]s?([il1o0öuü]s?){1,7}[r]s?[k]","regex: [d]s?[il1o0öuü]s?[r]s?[k]","psyonix","rocketleague","denekrid","dirkend","#fixitdirk","#dirkfixit"]
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #skydivegayguy_images: Personal Emotes (4 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #mrgamezombie1_images: Personal Emotes (10 emotes)
Socket closed. (Code: 1006, Reason: )
Using Socket Server: wss://andknuckles.frankerfacez.com/ [1:1]
Socket closed. (Code: 1006, Reason: )
Using Socket Server: wss://tuturu.frankerfacez.com/ [1:2]
Socket closed. (Code: 1006, Reason: )
Using Socket Server: wss://andknuckles.frankerfacez.com/ [1:1]
Socket Connected.
Error Saying Hello: Error: Expected array of string, string as arguments.
Socket Reply to 2 - SUCCESS -- undefined
Socket Reply to 3 - SUCCESS -- undefined
Socket Reply to 4 - SUCCESS -- undefined
Socket Reply to 5 - SUCCESS -- undefined
Socket Reply to 6 - SUCCESS -- undefined
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (5 emotes)
Adding Room: turtle
Socket Reply to 10 - SUCCESS -- undefined
Socket Reply to 12 - SUCCESS -- undefined
Error: There was an unknown error within Ember. [Error: Attempted to handle event `didSetProperty` on <web-client@model:stream::ember7501:turtle> while in state root.loading. Called with {name: viewers, oldValue: undefined, originalValue: undefined, value: 230}.]
Player Pause State for turtle: false
Player Pause State for turtle: false
Player Pause State for turtle: true
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (10 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (15 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (20 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (25 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (30 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #crimsonnn_images: Personal Emotes (5 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #cyberdog_k9000_images: Personal Emotes (35 emotes)
Socket Reply to 15 - SUCCESS -- undefined
Socket Reply to 16 - SUCCESS -- undefined
Socket Reply to 17 - SUCCESS -- undefined
Loading Follow Information for: dirkened
Found Following model.
Loading Follow Information for: dirkened
Adding Room: cobaltstreak
Socket Reply to 19 - SUCCESS -- undefined
Ext "BetterTTV": Loaded Emoticon Set #9004: Emoticons (2 emotes)
Ext "BetterTTV": Loaded Emoticon Set #9005: Emoticons (GIF) (5 emotes)
Socket Reply to 20 - SUCCESS -- undefined
Loading Follow Information for: cobaltstreak
Loading Follow Information for: cobaltstreak
Removing Room: jacobrl
Player Pause State for cobaltstreak: false
Removing Room: turtle
Socket Reply to 21 - SUCCESS -- undefined
Error: There was an error within an Ember RSVP. [undefined]
Error: There was an error within an Ember RSVP. [undefined]
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #tha_gary_images: Personal Emotes (10 emotes)
Ext "BetterTTV": SocketClient: Received Event
Ext "BetterTTV": [object Object]
Ext "BetterTTV": Loaded Emoticon Set #rezofsound_images: Personal Emotes (4 emotes)
Changed Setting "advanced_settings" to: true
Changed Setting "advanced_settings" to: true
Socket Reply to 26 - SUCCESS -- undefined
Socket Reply to 27 - SUCCESS -- undefined
Error: There was an unknown error within Ember. [TypeError: Cannot read property 'each' of undefined]
Error: There was an unknown error within Ember. [TypeError: Cannot read property 'each' of undefined]
Loading Follow Information for: dirkened
Loading Follow Information for: dirkened
Socket Reply to 28 - SUCCESS -- undefined
Socket Reply to 29 - SUCCESS -- undefined
Player Pause State for cobaltstreak: false
Error: There was an error within an Ember RSVP. [undefined]
Error: There was an error within an Ember RSVP. [undefined]
Changed Setting "advanced_settings" to: true

**Bug / Idea**:

FFZ does not automatically enable theater mode if you are going to a channel from the followers page
https://www.twitch.tv/directory/following

**Steps to Reproduce (if Applicable)**:

1. Have Automatic Theater Mode enabled 
2. Go to the page https://www.twitch.tv/directory/following
3. Choose a streamer to watch
4. When loading the channel, the stream won't be forced into theater mode

If you refresh the page, it will force theater mode

**Comment by SirStendec** [comment] 2016-10-11 05:08
Duplicate of #23

**Closed by SirStendec** 2016-10-11 05:08 UTC
