### ISSUE TITLE
Audio compressor button not showing on player since 23 April 2020

### ISSUE THREAD

**Issue by zxcq544** [FrankerFaceZ/FrankerFaceZ#789] opened 2020-04-24 01:40 UTC
**Describe the bug**
Near volume button there was always an audio compressor button. It is enabled in settings but doesn't show anywhere on player. It was fine until 23 april 2020.

**To Reproduce**
1. Go to 'twitch.com' any stream
2. Click on 'volume'
3. See no audio compressor button

**Expected behavior**
Audio compressor button in place

**Screenshots**
https://pastenow.ru/1386eaa74bf959328a8062eafff28dfd

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81
 - Other Extensions: AdBlock Plus, Volume Master

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Could not upload log - it halted in infinite upload.

**Comment by Gamertech** [comment] 2020-04-24 03:01
Can confirm this in Firefox 76.

**Comment by david0u** [comment] 2020-04-24 06:14
same on chrome too

**Comment by gaminggirl** [comment] 2020-04-24 10:02
Same on Firefox 75.0

**Comment by SirStendec** [comment] 2020-04-24 15:25
I believe this should be fixed as of b3266a2ef37c376a78dd7662d7a35bf2d60f0093

It's caused by an experiment with very few affected users, currently. There may be more experiments that I haven't noticed, but the first one I found caused exactly what users have been reporting to me.

Please let me know if this isn't fixed for you and I'll open it back up. Otherwise, closed!

**Closed by SirStendec** 2020-04-24 15:25 UTC
Labels: bug

**Comment by Gamertech** [comment] 2020-04-24 16:29
Compressor's back and functional again. Cheers

**Comment by Trung0246** [comment] 2020-05-21 01:26
Apparently the button didn't show on popout player (currently using latest Vivaldi version)
![image](https://user-images.githubusercontent.com/11626920/82512961-78da5c80-9ac6-11ea-883b-c9fdf9b35ecb.png)
