### ISSUE TITLE
Emotes doesn't show after the colon (:) when the colon not at the first ?

### ISSUE THREAD

**Issue by hxmo69** [FrankerFaceZ/FrankerFaceZ#1180] opened 2022-02-25 17:06 UTC
yesterday I was messing around in frankerface setting so much and after that this happened ... when type colon (:) to search for emote it appears only when the colon at the first of the message like this (:lul message) but when I go like this ( message :lul) the emote doesn't show up .. I displayed frankerface extension and still the same problem .

any help ?

**Comment by Codelefant** [comment] 2022-02-25 17:07
Most likely related to #1179

**Comment by Lordmau5** [comment] 2022-02-25 18:17
Yeah, duplicate of #1179

**Closed by Lordmau5** 2022-02-25 18:17 UTC
Labels: invalid
