### ISSUE TITLE
[bug] chat name color changing back to HSL Luma anytime I refresh or switch streams

### ISSUE THREAD

**Issue by sweagboi** [FrankerFaceZ/FrankerFaceZ#397] opened 2018-03-19 03:53 UTC
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BetterTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: not sure

**Bug / Idea**: Anytime i leave chat and come back (like when i check to see if someone is still live, or refresh the page) the names change back to HSL Luma, when I set it to Unchanged every time. It doesn't always say its changed, but after one message my name color changes back.
My name color is currently along the lines of maroon but it looks pink everytime it changes which is why this is so annoying.

I'm sure there's something I can do to fix this myself but i have no idea what

also the tiny settings window with every single tab defaulting to open is very annoying

**Steps to Reproduce (if Applicable)**: idk go to Following and go back to the channel you were watching

**Comment by SirStendec** [comment] 2018-03-19 16:29
You've indicated that you also use BetterTTV. BetterTTV has its own name color correction, independent of FFZ and FFZ's settings. You're almost certainly encountering that rather than a bug with FFZ.

**Comment by sweagboi** [comment] 2018-03-20 05:36
no it doesn’t. at least nothing i can find and the names change back when i’m messing with frankerfacez if it was BTTV it shouldn’t do that. the only option involving name colors in BTTV is disabling them completely

**Comment by sweagboi** [comment] 2018-03-20 05:49
even if BTTV is somehow causing Frankerz to do it, then there’s obviously some bug that’s causing FFZ to revert to default settings constantly

**Comment by SirStendec** [comment] 2018-03-21 04:53
The behavior you are describing is exactly the behavior I expect when you are also using BetterTTV. You aren't seeing any options in BTTV to control name highlighting because BTTV doesn't provide settings for several of its features. Chat color correction is one of those features.

Chat rendering when you have both extensions works like this:

1) Chat message is received and added to the chat message list. (Native Twitch)
2) A new chat line component is created by the chat container component for this new message. (Native Twitch)
3) The chat line component's render method is called. (Native Twitch)
4) FFZ overrides the chat line render method. This step builds the entire chat line, with FFZ's badges, emotes, name color corrections... everything. (FrankerFaceZ)
5) React does a DOM diff and sees that it needs to add the chat line to the page. So it does. (Native Twitch)
6) BetterTTV's MutationObserver notices a new element in the page and that it's a chat line. (BetterTTV)
7) BetterTTV processes the chat line. It injects its own badges and emotes if applicable. It does its own color calculations and overrides the color already set on the chat line. (BetterTTV)


When you change the username color setting with FFZ, this happens:

1) FFZ iterates over every chat line component that currently exists and calls `forceUpdate()` (FrankerFaceZ)
2) React schedules an update for each chat line. (Native Twitch)
3) The chat line component's render method is called. (Native Twitch)
4) FFZ overrides the chat line render method. This step builds the entire chat line, with FFZ's badges, emotes, name color corrections... everything. (FrankerFaceZ)
5) React does a DOM diff and sees that the chat line already exists. However, a few properties are different. It updates just those properties without injecting any new elements into the DOM. This reapplies FFZ's color calculations. (Native Twitch)
6) BetterTTV doesn't have a clue that anything happened and, as such, it does nothing. (BetterTTV)

The next time a chat line comes in, BetterTTV continues to act like it always does, making it look like FFZ's settings are broken or inconsistent. They're not.

I'm closing this issue. If you are in fact having an FFZ issue that you can reproduce with BetterTTV disabled, please open a new issue letting me know.

**Closed by SirStendec** 2018-03-21 04:53 UTC
Labels: invalid
