### ISSUE TITLE
Turning off Creative Showcase in the FFZ options removes video but keeps audio

### ISSUE THREAD

**Issue by TrampolineTales** [FrankerFaceZ/FrankerFaceZ#62] opened 2016-12-07 18:04 UTC
**Web Browser**:
Chrome 55.0.2883.75 m

**Do you use BetterTTV or other Twitch extensions**:
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTE3Nw.log

**Bug**:
Turning off Creative Showcase in the FFZ options removes the video but keeps audio playing on [twitch.tv/Creative](https://www.twitch.tv/directory/game/Creative).

**Steps to Reproduce (if Applicable)**:

Go to [twitch.tv/Creative](https://www.twitch.tv/directory/game/Creative) with this option set to off:
![](https://puu.sh/sHr7X/f047166d6c.png)

**Comment by SirStendec** [comment] 2016-12-07 22:59
Duplicate of #47

**Closed by SirStendec** 2016-12-07 22:59 UTC
