### ISSUE TITLE
ffz does not work in twitch dashboard chat

### ISSUE THREAD

**Issue by TheSqrtMinus1** [FrankerFaceZ/FrankerFaceZ#382] opened 2018-02-16 07:30 UTC
**Web Browser**:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
**Do you use BetterTTV or other Twitch extensions**:
bttv addon for ffz
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
n/a

**Bug / Idea**:
ffz does not work in twitch dashboard chat

**Steps to Reproduce (if Applicable)**:
go to https://twitch.tv/dashboard

**Comment by SirStendec** [comment] 2018-02-20 01:33
This is a known issue.

The problem is that Twitch's dashboard is now including non-legacy chat, powered by React. The site is otherwise their legacy codebase using Ember. Ember is supported by FFZv3. React is supported by FFZv4.

You can't have two instances of FFZ running in a tab at the same time, and I'm not able to spend the time now to do another re-implementation of chat features. I'm still not done with chat features in FFZv4.

For now, just use a pop-out. Position it over the dashboard if you like.

Leaving this open for visibility till the dashboard is finally brought into React.

**Comment by SirStendec** [comment] 2018-06-07 07:02
This issue can now be closed as Twitch finally ported their dashboard into the new codebase and things are able to work again.

**Closed by SirStendec** 2018-06-07 07:02 UTC
Labels: bug, old-twitch, wontfix
