### ISSUE TITLE
Channel title & game disappear when they update on a live channel.

### ISSUE THREAD

**Issue by winneon** [FrankerFaceZ/FrankerFaceZ#333] opened 2017-11-25 23:24 UTC
**Web Browser**: Firefox 57.0 Windows x64

**Do you use BetterTTV or other Twitch extensions**: The FFZ Add-on Pack

**Bug / Idea**: When a channel host updates their channel title or game when they are live, both the title and the game below the media player disappear on their channel page. This occurs on every channel, with or without the add-on pack.

**Steps to Reproduce (if Applicable)**: Because this occurs on every channel, it'll be a little difficult to consistently reproduce it because changing the channel title/game is only possible by the channel host themselves. Because of what seems like a Twitch bug, you cannot test this using your own channel because Twitch does not seem to update your own channel's title/game automatically if you're a viewer, at least it didn't for me no matter how much I tried.

**Comment by winneon** [comment] 2017-11-26 00:23
I managed to catch a channel updating their channel game mid-stream if this is helps you understand what I'm talking about. Halfway through the GIF, the channel game is updated to Rust but the whole left area just disappears as a result. https://gfycat.com/AstonishingDenseDuck

**Comment by SirStendec** [comment] 2017-11-26 16:48
Duplicate of #319

**Closed by SirStendec** 2017-11-26 16:48 UTC
