### ISSUE TITLE
Image thumbnail for imgur and youtube not working 

### ISSUE THREAD

**Issue by JordanDi123** [FrankerFaceZ/FrankerFaceZ#76] opened 2017-01-03 02:00 UTC
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: I use BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTI5MA.log

**Bug / Idea**: Not displaying the thumbnail

**Steps to Reproduce (if Applicable)**: Try to hover over the links and it will not show any image

**Comment by SirStendec** [comment] 2017-01-06 02:53
Duplicate of #15.

**Closed by SirStendec** 2017-01-06 02:53 UTC
Labels: bug, duplicate
