### ISSUE TITLE
Host button isn't showing

### ISSUE THREAD

**Issue by TTheenderr** [FrankerFaceZ/FrankerFaceZ#803] opened 2020-05-20 18:33 UTC
I have the settings in FFZ for the host button turned on, but yet it isn't showing.

**Environment (please complete the following information):**
 - OS: Windows 19
 - Browser: FireFox
 - Version 76
 - Other Extensions: BTTV, Avast

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

initialization
-------------------------------------------------------------------------------
[13:04:54] info | core: FrankerFaceZ v4.19.11 (build 2e5a3b42617fb07be342 - commit b3266a2ef37c376a78dd7662d7a35bf2d60f0093)
[13:04:54] info | settings: Using Provider: LocalStorageProvider
[13:04:54] info | site: Using: Twilight
[13:04:54] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[13:04:54] info | core: Loaded descriptions of 6 modules.
[13:04:54] info | site.fine: Installing MutationObserver.
[13:04:54] info | site: Loaded descriptions of 18 modules.
[13:04:54] info | settings: Initialization complete after 44.00000ms -- Values: 5 -- Profiles: 2
[13:04:54] info | socket: Using Server: wss://lilz.frankerfacez.com/
[13:04:54] info | raven: Installed error tracking.
[13:04:54] info | site.switchboard: Found Route and Switch with 11 routes.
[13:04:54] info | site.switchboard: Found Non-Matching Route /event/:teamName
[13:04:54] warn | site.switchboard: Error instantiating component for forced chunk loading. TypeError: e is undefined
[13:04:54] info | site.switchboard: Found Non-Matching Route /partner/signup
[13:04:54] info | site.web_munch: require() grabbed from invocation of module uHYy
[13:04:54] info | site.web_munch: require() grabbed in 437.00000ms.
[13:04:54] info | site.web_munch: Loaded names for 454 chunks from require().
[13:04:54] info | site.switchboard: Successfully forced a chunk to load using route /partner/signup
[13:04:54] info | main_menu: Built Tree in 16.00000ms with 133 structure nodes and 213 settings nodes.
[13:04:54] info | socket: Connected.
[13:04:54] info | socket: Server Time: 2020-05-20T18:04:57.236Z
[13:04:54] info | socket:  Local Time: 2020-05-20T18:04:54.732Z
[13:04:54] info | socket:   Est. Ping: 32.00000ms
[13:04:54] info | socket: Time Offset: -2.53698388671875
[13:04:54] info | experiments: Loaded information on 1 experiments.
[13:04:56] info | site.player: Skipping visibility hooks. Picture-in-Picture is not available.
[13:04:56] info | core: Initialization complete in 2603.00000ms.

settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
ffzenhancing.focus_input_area_after_emote_select: true
ffzenhancing.keep_delay_low: true
ffzenhancing.keep_delay_low_delay: 8.5
ffzenhancing.keep_delay_low_delay_low_latency: 5
ffzenhancing.keep_delay_low_rate: 1.05
ffzenhancing.fix_tooltips: false
ffzenhancing.doubleclick_username_paste_in_chat: false
ffzenhancing.move_users_in_chat_to_bottom: false
ffzenhancing.hide_rooms_header: false
ffzenhancing.auto_reload_on_error_2000: true
ffzenhancing.auto_reload_on_hanged_video: true
ffzenhancing.auto_reload_on_hanged_video_after: 4
ffzenhancing.auto_check_player_quality: false
ffzenhancing.pin_mentions: false
ffzenhancing.reset_after_delay: false
ffzenhancing.reset_after_delay_delay: 30
chat.bits.show: true
layout.display-bits-button: true
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.side-nav.hide-offline: false
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
channel.metadata.force-above: false
layout.portrait-invert: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
directory.show-channel-avatars: true
directory.hide-live: false
ffz.show-new-settings: true
chat.width: 340
chat.use-width: false
player.no-autoplay: false
player.home.autoplay: true
player.button.reset: true
player.compressor.enable: true
player.allow-catchup: true
player.compressor.default: false
player.theatre.auto-enter: false
metadata.host-button: true
player.volume-scroll: false
player.hide-squad-banner: false
chat.font-family: ""
chat.font-size: 12
chat.lines.alternate: false
chat.lines.borders: 0
chat.lines.emote-alignment: 0
chat.lines.padding: false
chat.timestamp-format: "h:mm"
chat.adjustment-contrast: 4.5
chat.adjustment-mode: 1
chat.banners.hype-train: true
chat.banners.polls: true
chat.community-chest.show: true
chat.hide-community-highlights: false
chat.subs.gift-banner: true
chat.emoji.style: "twitter"
chat.fix-bad-emotes: true
chat.rich.all-links: false
chat.rich.enabled: true
chat.rich.hide-tokens: true
chat.rich.minimum-level: 0
chat.subs.compact: false
chat.subs.merge-gifts: 1000
chat.subs.merge-gifts-visibility: false
chat.subs.show: 3
channel.hosting.enable: true
channel.raids.no-autojoin: false
metadata.featured-follow: true
metadata.player-stats: false
metadata.stream-delay-warning: 0
metadata.uptime: 1
sub-button.prime-notice: true
directory.hide-latest-videos: false
directory.hide-recommended: false
directory.hide-viewing-history: false
directory.following.group-hosts: true
directory.following.host-menus: 1

raven
-------------------------------------------------------------------------------
[3:39:57] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:57] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:57] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:57] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:57] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:39:57] LOG:info | gql: FFZ_EmoteMenu_SubStatus [55ms]
    {"variables":{"first":75,"after":null,"criteria":{"filter":"ALL"}}}
[3:39:57] UI | ui.click: button#emote-picker__emoji.ffz-tooltip.tw-block.tw-full-width.tw-interactable.tw-interactable--hover-enabled.tw-interactable--inverted.tw-interactive
[3:39:58] UI | ui.click: button#emote-picker__fav.ffz-tooltip.tw-block.tw-full-width.tw-interactable.tw-interactable--hover-enabled.tw-interactable--inverted.tw-interactive
[3:39:58] LOG:info | gql: GetBitsButton_Bits [106ms]
    {"variables":{"login":"","withChannel":false,"isLoggedIn":true}}
[3:39:58] LOG:info | gql: BitsConfigContext_Global [6ms]
    {}
[3:39:58] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=790015281363516527&instrumentation=%7B%22init-began-at%22%3A%225415%22%2C%22%2F_r-brtt%22%3A%22391%22%2C%22%2Fv1%2Fopen-brtt%22%3A%221471%22%2C%22%2Fv1%2Fpageview-brtt%22%3A%22493%22%2C%22%2Fv2%2Fevent%2Fcustom-brtt%22%3A%22662%22%7D -> 200
[3:39:58] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=790015281363516527&instrumentation=%7B%22%2F_r-brtt%22%3A%22222%22%2C%22%2Fv1%2Fhas-app-brtt%22%3A%22498%22%7D -> 200
[3:39:58] UI | ui.click: div.scrollable-area > div.simplebar-scroll-content > div.simplebar-content
[3:39:58] UI | ui.click: div.scrollable-area > div.simplebar-scroll-content > div.simplebar-content
[3:39:58] HTTP | xhr: GET https://api.betterttv.net/3/cached/emotes/global -> 200
[3:39:58] HTTP | xhr: GET https://api.betterttv.net/3/cached/frankerfacez/emotes/global -> 200
[3:39:58] HTTP | xhr: GET https://api.betterttv.net/3/cached/badges -> 200
[3:39:58] HTTP | xhr: GET https://api.betterttv.net/3/cached/users/twitch/463439177 -> 404
[3:39:58] HTTP | xhr: GET https://api.betterttv.net/3/cached/frankerfacez/users/twitch/463439177 -> 200
[3:39:58] UI | ui.click: button.tw-align-items-center.tw-align-middle.tw-border-bottom-left-radius-medium.tw-border-bottom-right-radius-medium.tw-border-top-left-radius-medium.tw-border-top-right-radius-medium.tw-button-icon.tw-button-icon--overlay.tw-core-button.tw-core-button--overlay.tw-inline-flex.tw-interactive.tw-justify-content-center.tw-overflow-hidden.tw-relative
[3:39:58] UI | ui.click: div.click-handler.tw-absolute.tw-bottom-0.tw-left-0.tw-right-0.tw-top-0
[3:39:58] UI | ui.click: div.click-handler.tw-absolute.tw-bottom-0.tw-left-0.tw-right-0.tw-top-0
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:39:58] UI | ui.click: div.tw-flex.tw-flex-column.tw-full-width.tw-mg-b-05 > div > div
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:39:58] UI | ui.click: div.tw-flex.tw-flex-column.tw-full-width.tw-mg-b-05 > div > div
[3:39:58] LOG:info | gql: updateUserViewedVideo [44ms]
    {"variables":{"input":{"userID":"134791568","position":4120,"videoID":"38177500224","videoType":"LIVE"}}}
[3:39:58] HTTP | xhr: GET https://api2.branch.io/v1/has-app/key_live_jgBdao5vVtyZ3hdckxy8jlkkzqooQltZ?browser_fingerprint_id=790015281363516527&instrumentation=%7B%22%2F_r-brtt%22%3A%22125%22%2C%22%2Fv1%2Fhas-app-brtt%22%3A%22550%22%7D -> 200
[3:39:58] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:39:58] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] LOG:info | gql: FollowedChannels [92ms]
    {"variables":{"limit":100,"cursor":""}}
[3:39:58] UI | ui.click: p.tw-c-text-alt-2
[3:39:58] LOG:info | gql: FFZ_GetEmoteInfo [23ms]
    {"variables":{"id":"12"}}
[3:39:58] LOG:info | gql: FFZ_GetEmoteInfo [28ms]
    {"variables":{"id":"3"}}
[3:39:58] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.click: div.tw-border-t > div.tw-flex.tw-justify-content-between.tw-relative
[3:39:58] UI | ui.click: button.tw-align-items-center.tw-align-middle.tw-border-bottom-left-radius-medium.tw-border-bottom-right-radius-medium.tw-border-top-left-radius-medium.tw-border-top-right-radius-medium.tw-button-icon.tw-button-icon--overlay.tw-core-button.tw-core-button--overlay.tw-inline-flex.tw-interactive.tw-justify-content-center.tw-overflow-hidden.tw-relative
[3:39:58] LOG:info | gql: VideoPlayerStreamInfoOverlayChannel [57ms]
    {"variables":{"channel":"voxpopgames"}}
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:39:58] LOG:info | gql: TopNavUserMenuDropdownQuery [114ms]
    {"variables":{"login":"ttheenderr_"}}
[3:39:58] UI | ui.click: div.tw-flex-grow-0
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg
[3:39:58] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:39:58] LOG:info | gql: RealtimeStreamTagList [65ms]
    {"variables":{"channelLogin":"voxpopgames"}}
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] LOG:info | gql: RecommendedChannels [142ms]
    {"variables":{"first":10,"recID":"9760fbcf-1663-426d-be10-9d2bf563d18f","location":"LEFT_NAV","context":{"platform":"web"},"includePromo":false}}
[3:39:58] LOG:info | gql: FollowedChannels [83ms]
    {"variables":{"limit":100,"cursor":""}}
[3:39:58] UI | ui.click: div.tw-aspect.tw-aspect--align-top > svg > g > path
[3:39:58] UI | ui.click: div.tw-align-items-center.tw-flex.tw-pd-05.tw-relative > div.tw-flex-grow-1
[3:39:58] UI | ui.click: div.tw-align-items-center.tw-flex > div.tw-toggle > label.tw-toggle__button
[3:39:58] UI | ui.click: input#ce96805d184f68156f5e587735813a81.tw-toggle__input[type="checkbox"]
[3:39:58] UI | ui.click: div.click-handler.tw-absolute.tw-bottom-0.tw-left-0.tw-right-0.tw-top-0
[3:39:58] UI | ui.click: div.tw-button-icon__icon > figure.ffz-player-icon.ffz-i-t-reset
[3:39:58] UI | ui.click: div.tw-button-icon__icon > figure.ffz-player-icon.ffz-i-t-reset-clicked
[3:39:58] LOG:info | gql: StreamRefetchManager [40ms]
    {"variables":{"channel":"voxpopgames"}}
[3:39:58] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:39:58] LOG:info | gql: updateUserViewedVideo [51ms]
    {"variables":{"input":{"userID":"134791568","position":4584,"videoID":"38177500224","videoType":"LIVE"}}}
[3:39:58] UI | ui.click: button.tw-align-items-center.tw-align-middle.tw-border-bottom-left-radius-medium.tw-border-bottom-right-radius-medium.tw-border-top-left-radius-medium.tw-border-top-right-radius-medium.tw-button-icon.tw-core-button.tw-core-button--border.tw-inline-flex.tw-interactive.tw-justify-content-center.tw-overflow-hidden.tw-relative
[3:39:58] LOG:info | main_menu: Built Tree in 10.00000ms with 133 structure nodes and 213 settings nodes.
[3:39:58] UI | ui.click: span.tw-flex-grow-1
[3:39:58] UI | ui.click: span.tw-flex-grow-1
[3:39:58] UI | ui.click: input#ffz-main-menu.search.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-input.tw-pd-l-3.tw-pd-r-1.tw-pd-y-05[type="search"]
[3:39:58] UI | ui.input: input#ffz-main-menu.search.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-input.tw-pd-l-3.tw-pd-r-1.tw-pd-y-05[type="search"]
[3:39:58] UI | ui.click: span.tw-flex-grow-1
[3:39:58] UI | ui.click: span.tw-flex-grow-1
[3:39:58] UI | ui.click: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.input: textarea.tw-block.tw-border-radius-medium.tw-font-size-6.tw-full-width.tw-textarea.tw-textarea--no-resize
[3:39:58] UI | ui.click: span.tw-flex-grow-1
[3:39:58] UI | ui.click: button.tw-button-icon.tw-mg-x-05
[3:39:58] HTTP | fetch: GET https://static.twitchcdn.net/config/manifest.json?v=1 -> 200
[3:39:58] HTTP | xhr: POST https://api2.branch.io/v2/event/custom -> 200
[3:39:58] UI | ui.click: span.tw-button-icon__icon > figure.ffz-i-zreknarf
[3:39:58] LOG:info | main_menu: Built Tree in 12.00000ms with 133 structure nodes and 213 settings nodes.
[3:39:58] LOG:info | gql: FollowedChannels [99ms]
    {"variables":{"limit":100,"cursor":""}}
[3:39:58] UI | ui.click: span.tw-flex-grow-1

experiments
-------------------------------------------------------------------------------
Unique ID: f11db26d4f395e88

FFZ | New API Stress Testing: true
TWITCH | Community_Gifting_Bundle_Presentment: control
TWITCH | vx_two_browse: control
TWITCH | paypal_first_v2: control
TWITCH | ABRNetworkLinkFilter: control
TWITCH | twilight_settings_labelling: rest
TWITCH | its_the_remix_to_position: control
TWITCH | emote_good_standing: off
TWITCH | gift_x_more: control
TWITCH | twilight_quarterly_streamer_survey_for_new_streamers: Control
TWITCH | extensions_pick_up_where_you_left_off: test
TWITCH | cf_high_top_3peat: control
TWITCH | bl3_suggested: control
TWITCH | multi_month_subs: variant_fpso_40
TWITCH | take_the_leaderboard: TakeTopSpot
TWITCH | prowse_li_intelshelf: control
TWITCH | vod_q_tip: control
TWITCH | bits_skus_reduction: control
TWITCH | prowse_debug_us: control
TWITCH | ads_multiplayer_experiment: no_ui
TWITCH | vx_prod_left_nav_hover_expand: control
TWITCH | disco_directory_titles: control
TWITCH | prowse_li: variant2
TWITCH | disco_max_width: variant1
TWITCH | grandpere: enhanced
TWITCH | TWILIGHT_VOD_KIRK: top
TWITCH | cg_3_bundle: control
TWITCH | Player Core WASM experiment: wasm
TWITCH | twilight_vod_editing_youre_welcome: control
TWITCH | theatre-mode-social-panel-v2: variant_a
TWITCH | twilight_quarterly_streamer_survey_for_partners: Control
TWITCH | sunlight_dashboard: control
TWITCH | twilight_subs_prime_2_paid: variant_a
TWITCH | gem_gem_gem_gem: control
TWITCH | cg_sku_no_ml_2: control
TWITCH | sub_mgmt_modal: control
TWITCH | TWILIGHT_AAX_DISPLAY: no
TWITCH | watch_stunt_double: control
TWITCH | twilight_channel_analytics_content_overlap_panels: yes
TWITCH | vxp_blockbuster: control
TWITCH | cf_three_stock_boba: control
TWITCH | VP09 Web: control
TWITCH | disco_hol_up: control
TWITCH | emote_card_sub_button: sub_button
TWITCH | Twilight Player Core NPM Distribution (Staff): variant-b
TWITCH | LIHP_rec_leftnav: variant1
TWITCH | nielsen_analytics: active
TWITCH | twilight_channel_analytics_notifications_analytics: treatment
TWITCH | Twilight Player Core NPM Distribution (Public): variant-a
TWITCH | mobile_native_chat_filter_existing_users: opt-in
TWITCH | vod_damian: control
TWITCH | mischief_left: control
TWITCH | twilight_quarterly_streamer_survey_for_affiliates: Control
TWITCH | ABRObserveredBitrates: control
TWITCH | extension_panel_recommendations_monetization: test
TWITCH | vx_two_front: control
TWITCH | watch_suggest_username: control
TWITCH | emote_card: treatment
TWITCH | vx_prod_image_upscale: control
TWITCH | disco_blues: ex_bar
TWITCH | prowse_lo_intelshelf: control
TWITCH | TWILIGHT_VOD_TOP_SHELF: control
TWITCH | extension_overlay_improvement: active
TWITCH | vx_prod_braavos_web: grid_variant
TWITCH | WARP_IPv6: control
TWITCH | prowse_debug_lo: control
TWITCH | liverecs_holdout_device: control
TWITCH | TWILIGHT_CAROUSEL_HOLDBACK: control
TWITCH | TWILIGHT_EXTENDED_PRESENCE: control
TWITCH | channel_level_chat_visibility: control
TWITCH | vxp_mandatory_email_verification: control
TWITCH | Community_Gifting_Offer_Presentment: treatment
TWITCH | bits_landing_page: control
TWITCH | private_callout_redesign: variant2
TWITCH | twilight_prime_gift_bomb_dashboard_device: control
TWITCH | twilight_chat_connection: control
TWITCH | TWILIGHT_SUBS_AFFILIATE_BADGES: affiliate_access
TWITCH | watch_stunt_double_user: variant
TWITCH | subs_benefit_reminder: control
TWITCH | WARP_IPv4: control
TWITCH | prowse_lo_again: variant2
TWITCH | community_gifting_recommendations: control
TWITCH | apex_legends_tags: force
TWITCH | abr_fastslow_web: control
TWITCH | twilight_stream_summary_use_kite: no
TWITCH | Devsite_create_apps_form_recaptcha: control
TWITCH | TWILIGHT_ARCHER: moments_with_images
TWITCH | extension_panel_recommendations: test
TWITCH | xo_benefits: variant_1_no_benefits
TWITCH | sub_reanimator_2: variant_a
TWITCH | vxp_thunderdome_logged_in: treatment
TWITCH | mobile_native_chat_filter_new_users: opt-out
TWITCH | placement_promotions_pos: control
TWITCH | personalized_sub_modal_p1: no_benefits_text
TWITCH | twilight_subs_share_resub: control
TWITCH | celebi: control
TWITCH | vx_onboarding_recs: treatment
TWITCH | twilight_use_kite: no
TWITCH | new_search_backend: control
TWITCH | LOHP_rec_leftnav: variant1
TWITCH | vxp_thunderdome_logged_out: treatment
TWITCH | fun_captcha_experiment: treatment
TWITCH | twilight_clips_on_the_brain: control
TWITCH | sub_modal_2: dirty_modal
TWITCH | cf_five_stack_in_ripcity: control
TWITCH | vod_high_ground: variant1
TWITCH | TWILIGHT_AD_DENSITY_WIDGET: no
TWITCH | subs_pif: thank_first
TWITCH | ad_loudness_real_time: treatment_only_down
TWITCH | bits_enabled_extension_recommendation: t1
TWITCH | chat_rejoin_rewrite: variant
TWITCH | settings_overlay_indicator: control

addons
-------------------------------------------------------------------------------
Known
deck | disabled | Deck v1.0.2
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.1
ffzap-core | disabled | FFZ:AP BTTV v3.2.1
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.0
poll-shim | disabled | poll_shim v0.1.3
smokemotes | disabled | smokEmotes v0.0.11

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | raven
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
unloaded | disabled | translation_ui
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.channel_bar
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.theme
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.following
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.player
unloaded | disabled | site.settings_sync
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffz-enhancing-addon

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.media-queries: true
chat.badges.version: 2
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: true
chat.lines.alternate: false
chat.lines.padding: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
chat.filtering.highlight-mentions: false
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.width: 340
chat.font-size: 12
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.tab-complete.emotes-without-colon: false
chat.actions.room-above: false
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.polls: true
chat.emote-menu.sort-emotes: 0
chat.emote-menu.sort-tiers-last: true
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.points.show-button: true
chat.points.show-rewards: true
chat.actions.room: []
chat.bits.animated: true
theme.tooltips-dark: false
chat.fix-bad-emotes: true
chat.filtering.highlight-basic-users-blocked: []
chat.filtering.highlight-basic-users-blocked--regex: null
chat.filtering.highlight-basic-badges-blocked: []
chat.filtering.highlight-basic-badges-blocked--list: null
chat.filtering.highlight-basic-blocked: []
chat.filtering.highlight-basic-blocked--regex: null
chat.filtering.highlight-basic-users: []
chat.filtering.highlight-basic-users--color-regex: null
chat.filtering.highlight-basic-badges: []
chat.filtering.highlight-basic-badges--colors: null
chat.filtering.highlight-basic-terms: []
chat.filtering.highlight-basic-terms--color-regex: null
chat.filtering.display-deleted: false
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.all-links: false
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.mru.enabled: true
chat.filtering.process-own: false
chat.emote-menu.reduced-padding: false
chat.emote-menu.combine-tabs: false
chat.emote-menu.default-tab: "channel"
chat.emote-menu.show-search: true
chat.emote-menu.show-heading: 1
tooltip.images: true
tooltip.emote-images: true
tooltip.badge-images: true
tooltip.emote-sources: true
tooltip.link-images: true

**Additional context**

**Comment by SirStendec** [comment] 2020-05-27 19:51
Duplicate of #794

**Closed by SirStendec** 2020-05-27 19:51 UTC
Labels: bug
